// The grammar of the season, one point at a time. Each point has its note (one Romanian line, examples with **x**)
// and a bank of practice sentences for training: [text with {}, right, wrong options, why]. Wrong options are the
// mistakes Romanian speakers really make. Review ids are 'g:<id>'.

export const GRAMMAR = {
  be: { ep: 1, title: 'to be: am, is, are',
    note: ['I am, you are, he/she/it is. La întrebare, verbul trece în față.', ['**Are** you cold?', 'It**’s** my garden.']],
    bank: [
      ['{} you hungry?', 'Are', ['Have', 'You are'], 'Foamea merge cu be: Are you hungry?'],
      ['Mimi {} my cat.', 'is', ['are', 'am'], 'Mimi = she: is.'],
      ['I {} thirty years old.', 'am', ['have', 'has'], 'Vârsta merge cu be: I am thirty.'],
      ['{} very cold tonight.', 'It’s', ['Is', 'It'], 'Propoziția are subiect și verb: It’s cold.'],
      ['Where {} my keys?', 'are', ['is', 'am'], 'Keys e plural: are.'],
      ['The people on this street {} very nice.', 'are', ['is', 'am'], 'People e plural: people are.'],
      ['{} Tom at the café?', 'Is', ['Are', 'Does'], 'Întrebare cu be: Is Tom…?'],
      ['I {} with you.', 'agree', ['am agree', 'agreeing'], 'Agree e verb: I agree, fără „am”.'],
    ] },
  'have-got': { ep: 1, title: 'have got, has got',
    note: ['Ce ai: I have got (I’ve got). He, she, it: has got. Negativ: haven’t got, hasn’t got.', ['I**’ve got** a cat.', 'It **has got** one spark.']],
    bank: [
      ['My lantern {} got one spark.', 'has', ['have', 'is'], 'Lantern = it: has got.'],
      ['I {} got a torch on my phone.', 'have', ['has', 'am'], 'Cu I: have got.'],
      ['{} you got a pen?', 'Have', ['Do', 'Has'], 'Întrebare: Have you got…?'],
      ['Sorry, I {} got any money.', 'haven’t', ['don’t', 'hasn’t'], 'Negativ: I haven’t got.'],
      ['Priya {} got a small shop.', 'has', ['have', 'is'], 'Priya = she: has got.'],
      ['We {} got a big garden.', 'have', ['has', 'are'], 'We: have got.'],
      ['{} Mimi got green eyes?', 'Has', ['Have', 'Does'], 'Mimi = she: Has she got…?'],
      ['The Stranger {} got a name. Not yet.', 'hasn’t', ['haven’t', 'isn’t'], 'He/she/it: hasn’t got.'],
    ] },
  'this-that': { ep: 1, title: 'this, that, these, those',
    note: ['This, these: aproape. That, those: departe. These și those sunt la plural.', ['**This** is my phone.', '**Those** are stars.']],
    bank: [
      ['{} are my keys, here in my hand.', 'These', ['This', 'Those'], 'Aproape și plural: these.'],
      ['Look up! {} is the moon.', 'That', ['This', 'These'], 'Departe și una: that.'],
      ['{} are stars, very far away.', 'Those', ['These', 'That'], 'Departe și plural: those.'],
      ['{} is my cup. I’m holding it.', 'This', ['That', 'These'], 'Aproape și una: this.'],
      ['Who are {} people over there?', 'those', ['these', 'that'], 'Departe și plural: those.'],
      ['{} apples here are very good.', 'These', ['This', 'Those'], 'Aproape și plural: these.'],
    ] },
  'ps-s': { ep: 2, title: 'prezentul simplu: -s la he, she, it',
    note: ['Ce faci de obicei: prezentul simplu. La he, she, it verbul primește -s.', ['I **drink** tea.', 'Tom **makes** tea.']],
    bank: [
      ['Tom {} the café at six.', 'opens', ['open', 'is open'], 'Tom = he: opens, cu -s.'],
      ['I usually {} tea with milk.', 'drink', ['drinks', 'drinking'], 'Cu I verbul rămâne simplu.'],
      ['Priya {} in a shop.', 'works', ['work', 'working'], 'Priya = she: works.'],
      ['Mimi {} on the blanket every day.', 'sleeps', ['sleep', 'is sleep'], 'Mimi = she: sleeps.'],
      ['My parents {} in Romania.', 'live', ['lives', 'living'], 'They: fără -s.'],
      ['Sam {} the night bus.', 'drives', ['drive', 'driving'], 'Sam = he: drives.'],
      ['She {} two languages.', 'speaks', ['speak', 'is speak'], 'She: speaks.'],
      ['The café {} at six.', 'closes', ['close', 'is close'], 'The café = it: closes.'],
      ['Tom {} very good tea.', 'makes', ['make', 'making'], 'Tom = he: makes, cu -s.'],
    ] },
  'do-does': { ep: 2, title: 'întrebări și negații: do, does',
    note: ['La întrebare și negație: do, sau does la he, she, it. După does verbul nu mai are -s.', ['What **do** you drink?', '**Does** Mimi like milk? She **doesn’t**.']],
    bank: [
      ['{} Tom work on Sundays?', 'Does', ['Do', 'Is'], 'Tom = he: Does Tom work?'],
      ['{} you like coffee?', 'Do', ['Does', 'Are'], 'You: Do you like…?'],
      ['She doesn’t {} milk.', 'like', ['likes', 'liking'], 'După doesn’t, verbul e fără -s.'],
      ['Where {} Priya live?', 'does', ['do', 'is'], 'Priya = she: Where does she live?'],
      ['I {} understand.', 'don’t', ['doesn’t', 'not'], 'Negativ cu I: don’t.'],
      ['Mimi {} like the rain.', 'doesn’t', ['don’t', 'isn’t'], 'Mimi = she: doesn’t.'],
      ['What time {} the bus come?', 'does', ['do', 'is'], 'The bus = it: does.'],
      ['Does Sam {} at night?', 'work', ['works', 'working'], 'După does: work, fără -s.'],
    ] },
  pc: { ep: 3, title: 'prezentul continuu: am, is, are + -ing',
    note: ['Ce se întâmplă acum: am, is, are + verbul cu -ing.', ['Look! Mimi **is sleeping**.', 'What **are** you **doing**?']],
    bank: [
      ['Look! Tom {} some boxes.', 'is carrying', ['carries', 'carrying'], 'Look!: se întâmplă acum: is carrying.'],
      ['What {} you doing?', 'are', ['do', 'is'], 'You: are you doing.'],
      ['Shh! The baby {}.', 'is sleeping', ['sleeps', 'sleeping'], 'Acum: is sleeping.'],
      ['I {} for my keys. Have you seen them?', 'am looking', ['look', 'looking'], 'Chiar acum: am looking.'],
      ['They {} TV at the moment.', 'are watching', ['watch', 'is watching'], 'At the moment: are watching.'],
      ['It {} now. Take an umbrella.', 'is raining', ['rains', 'raining'], 'Acum: is raining.'],
      ['She {} on the phone right now.', 'is talking', ['talks', 'talking'], 'Right now: is talking.'],
    ] },
  'pc-ps': { ep: 3, title: 'acum sau de obicei?',
    note: ['De obicei: prezentul simplu (every day, usually). Chiar acum: prezentul continuu (now, look!).', ['Sam **drives** the bus every night.', 'Now he **is sleeping**.']],
    bank: [
      ['Sam {} the bus every night.', 'drives', ['is driving', 'drive'], 'Every night: de obicei: drives.'],
      ['Right now Sam {}.', 'is sleeping', ['sleeps', 'sleep'], 'Right now: is sleeping.'],
      ['I usually {} to work.', 'walk', ['am walking', 'walking'], 'Usually: prezentul simplu.'],
      ['Listen! Somebody {} the piano.', 'is playing', ['plays', 'play'], 'Listen!: acum: is playing.'],
      ['I {} what you mean.', 'know', ['am knowing', 'knowing'], 'Know nu se pune la -ing: I know.'],
      ['Priya {} the newspaper every morning.', 'reads', ['is reading', 'read'], 'Every morning: reads.'],
      ['Do you {} this song?', 'like', ['liking', 'are liking'], 'Like nu se pune la -ing.'],
    ] },
  'past-ed': { ep: 4, title: 'trecutul: -ed',
    note: ['Ce s-a întâmplat și s-a terminat: verbul + -ed. Aceeași formă pentru toate persoanele.', ['The bus **stopped**.', 'I **walked** home.']],
    bank: [
      ['The bus {} at the stop.', 'stopped', ['stoped', 'stops'], 'Stop dublează p-ul: stopped.'],
      ['I {} my mum yesterday.', 'called', ['call', 'was call'], 'Yesterday: called.'],
      ['What {} last night?', 'happened', ['happens', 'was happen'], 'Trecut: happened.'],
      ['We {} at home all day.', 'stayed', ['staied', 'stay'], 'Stay + ed: stayed.'],
      ['The bus {} late.', 'arrived', ['arrive', 'arriveed'], 'Arrive + d: arrived.'],
      ['She {} to the window.', 'walked', ['walks', 'was walk'], 'Trecut: walked.'],
      ['I {} to fix it, but I couldn’t.', 'tried', ['tryed', 'try'], 'Try → tried.'],
      ['He {} his phone and smiled.', 'checked', ['check', 'was check'], 'Trecut: checked.'],
    ] },
  'was-were': { ep: 4, title: 'was, were',
    note: ['Trecutul lui be: I, he, she, it was; you, we, they were.', ['It **was** very quiet.', 'There **were** no people.']],
    bank: [
      ['It {} very quiet last night.', 'was', ['were', 'is'], 'It: was.'],
      ['The streets {} empty.', 'were', ['was', 'are'], 'Plural: were.'],
      ['{} you at home yesterday?', 'Were', ['Was', 'Did'], 'You: were.'],
      ['I {} tired after work.', 'was', ['were', 'did'], 'I: was.'],
      ['Where {} Sam at midnight?', 'was', ['were', 'did'], 'Sam = he: was.'],
      ['We {} on the bus.', 'were', ['was', 'are'], 'We: were.'],
    ] },
  'there-is': { ep: 5, title: 'there is, there are',
    note: ['Există: there is la singular, there are la plural.', ['**There is** a spark in the jar.', '**There are** some candles.']],
    bank: [
      ['{} a shop on the corner.', 'There is', ['There are', 'Is'], 'Există = there is. Nu se începe doar cu is.'],
      ['{} some eggs in the fridge.', 'There are', ['There is', 'They are'], 'Eggs, plural: there are.'],
      ['{} any milk?', 'Is there', ['Are there', 'There is'], 'Întrebare: Is there…?'],
      ['{} two buses every hour.', 'There are', ['There is', 'Are'], 'Plural: there are.'],
      ['{} a problem with the lift.', 'There is', ['It has', 'There are'], 'O problemă: there is.'],
      ['{} many people on the bus?', 'Were there', ['Was there', 'There were'], 'Trecut, plural: were there.'],
    ] },
  'some-any': { ep: 5, title: 'some, any',
    note: ['Some în propoziții afirmative. Any la întrebări și negații.', ['I need **some** candles.', 'Have you got **any** batteries?']],
    bank: [
      ['I need {} batteries.', 'some', ['any', 'a'], 'Afirmativ: some.'],
      ['I haven’t got {} candles.', 'any', ['some', 'no'], 'Negativ: any.'],
      ['There isn’t {} milk.', 'any', ['some', 'no'], 'Negativ: any.'],
      ['There’s {} milk in the fridge.', 'some', ['any', 'a'], 'Afirmativ: some. Milk nu se numără, deci fără a.'],
      ['We haven’t got {} bread.', 'any', ['some', 'no'], 'Negativ: any.'],
      ['There are {} coins in the jar.', 'some', ['any', 'a'], 'Afirmativ: some.'],
    ] },
  'much-many': { ep: 5, title: 'much, many',
    note: ['Many pentru ce se numără (apples, coins). Much pentru ce nu se numără (milk, money, time).', ['How **many** candles?', 'How **much** money?']],
    bank: [
      ['How {} money have you got?', 'much', ['many', 'lot'], 'Money nu se numără: much.'],
      ['How {} eggs do we need?', 'many', ['much', 'lot'], 'Eggs se numără: many.'],
      ['We haven’t got {} time.', 'much', ['many', 'lots'], 'Time: much.'],
      ['There aren’t {} people here.', 'many', ['much', 'lot'], 'People se numără: many.'],
      ['How {} sugar do you want?', 'much', ['many', 'lot'], 'Sugar: much.'],
      ['Can you give me some {}?', 'information', ['informations', 'an information'], 'Information nu are plural.'],
      ['She gave me some good {}.', 'advice', ['advices', 'an advice'], 'Advice nu are plural.'],
      ['How {} coins are in the jar?', 'many', ['much', 'lot'], 'Coins se numără: many.'],
    ] },
  prep: { ep: 6, title: 'unde e? in, on, under, behind…',
    note: ['Locul: in (în), on (pe), under (sub), behind (în spatele), in front of (în fața), next to (lângă), between (între).', ['The key is **under** the pot.', 'The spark is **in front of** the gnome.']],
    bank: [
      ['The cat is sleeping {} the sofa.', 'on', ['in', 'at'], 'Pe canapea: on the sofa.'],
      ['The keys are {} my bag.', 'in', ['on', 'at'], 'În geantă: in.'],
      ['The ball is {} the table.', 'under', ['below of', 'down'], 'Sub masă: under.'],
      ['The shed is {} the house.', 'behind', ['after', 'back'], 'În spatele: behind.'],
      ['Wait for me {} the café.', 'in front of', ['in front', 'before'], 'În fața: in front of.'],
      ['The bank is {} the shop and the café.', 'between', ['among', 'in'], 'Între două: between.'],
      ['I sat {} Tom on the bus.', 'next to', ['next', 'near of'], 'Lângă: next to.'],
      ['We were {} home all evening.', 'at', ['in', 'to'], 'Acasă: at home.'],
      ['I met Sam {} the bus.', 'on', ['in', 'at'], 'În autobuz: on the bus.'],
    ] },
  'past-irr': { ep: 7, title: 'trecutul verbelor neregulate',
    note: ['Multe verbe au trecutul lor, fără -ed: go → went, see → saw, take → took. Se învață pe de rost.', ['I **went** to the shop.', 'She **saw** a light.']],
    bank: [
      ['Yesterday I {} to the market.', 'went', ['goed', 'gone'], 'Go → went.'],
      ['She {} a light in the sky.', 'saw', ['seed', 'seen'], 'See → saw.'],
      ['He {} me the key.', 'gave', ['gived', 'given'], 'Give → gave.'],
      ['We {} the bus home.', 'took', ['taked', 'taken'], 'Take → took.'],
      ['Tom {} “Good morning!”', 'said', ['sayed', 'told'], 'Say → said. Tell are nevoie de cineva: told me.'],
      ['She {} me a story.', 'told', ['said', 'telled'], 'Tell someone something: told me.'],
      ['I {} a new phone last week.', 'bought', ['buyed', 'brought'], 'Buy → bought. Brought vine de la bring.'],
      ['I {} your keys under the sofa!', 'found', ['finded', 'fund'], 'Find → found.'],
    ] },
  did: { ep: 7, title: 'întrebări și negații la trecut: did',
    note: ['La trecut, întrebarea și negația se fac cu did. După did, verbul e la forma de bază.', ['**Did** you **see** it?', 'I **didn’t go**.']],
    bank: [
      ['{} you see the light last night?', 'Did', ['Do', 'Were'], 'Last night, trecut: Did you see…?'],
      ['I didn’t {} anything.', 'hear', ['heard', 'hearing'], 'După didn’t: forma de bază.'],
      ['Where did you {} it?', 'find', ['found', 'finding'], 'După did: find.'],
      ['She {} come to the party yesterday.', 'didn’t', ['doesn’t', 'wasn’t'], 'Yesterday, trecut negativ: didn’t.'],
      ['What did Tom {}?', 'say', ['said', 'says'], 'După did: say.'],
      ['{} Mrs Hughes tell you yesterday?', 'Did', ['Was', 'Does'], 'Yesterday, trecut: Did she tell…?'],
    ] },
  pp: { ep: 8, title: 'prezentul perfect: have + participiu',
    note: ['Ceva din trecut care contează acum, fără un moment exact: have/has + participiu. Ever = vreodată, never = niciodată.', ['**Have** you ever **seen** it?', 'I**’ve never been** there.']],
    bank: [
      ['{} you ever seen a falling star?', 'Have', ['Did', 'Are'], 'Ever, fără moment exact: Have you ever seen…?'],
      ['I’ve never {} to London.', 'been', ['went', 'go'], 'Never + participiu: been.'],
      ['She {} lost her keys again.', 'has', ['have', 'is'], 'She: has lost.'],
      ['We have {} this song before.', 'heard', ['hear', 'hearing'], 'Participiu: heard.'],
      ['Have you {} your homework?', 'done', ['did', 'do'], 'Participiu: done.'],
      ['I’ve just {} Tom.', 'seen', ['saw', 'see'], 'Just + participiu: seen.'],
      ['Tom has {} tea for us.', 'made', ['maked', 'make'], 'Make → made.'],
    ] },
  'for-since': { ep: 8, title: 'for și since',
    note: ['For + cât timp (for ten years). Since + de când (since 1966, since Monday).', ['I’ve lived here **for** ten years.', '… **since** 1966.']],
    bank: [
      ['She has lived here {} 1966.', 'since', ['for', 'from'], 'De când: since 1966.'],
      ['I’ve known Tom {} ten years.', 'for', ['since', 'from'], 'Cât timp: for ten years.'],
      ['We’ve been here {} Monday.', 'since', ['for', 'from'], 'De luni: since Monday.'],
      ['He’s worked there {} a long time.', 'for', ['since', 'during'], 'Cât timp: for.'],
      ['I haven’t seen her {} last summer.', 'since', ['for', 'from'], 'De când: since.'],
      ['I’ve had this coat {} years.', 'for', ['since', 'from'], 'Cât timp: for years.'],
    ] },
  'pp-past': { ep: 8, title: 'prezent perfect sau trecut?',
    note: ['Cu un moment din trecut (yesterday, in 1966, last week): trecutul simplu. Fără moment, sau până acum: prezentul perfect.', ['I **saw** him **yesterday**.', 'I**’ve seen** him **before**.']],
    bank: [
      ['I {} him yesterday.', 'saw', ['have seen', 'see'], 'Yesterday: trecut simplu: saw.'],
      ['In 1966 she {} a light in the sky.', 'saw', ['has seen', 'sees'], 'In 1966: trecut simplu.'],
      ['I {} this film before. It’s great.', 'have seen', ['see', 'am seeing'], 'Before, fără moment exact: have seen.'],
      ['When {} you arrive?', 'did', ['have', 'are'], 'When întreabă de un moment: did.'],
      ['She {} here since 1966.', 'has lived', ['lived', 'lives'], 'Since, până acum: has lived.'],
      ['Last week Priya {} some old coins.', 'found', ['has found', 'finds'], 'Last week: found.'],
    ] },
  will: { ep: 9, title: 'will',
    note: ['Will pentru ce hotărăști acum, ce promiți și ce crezi că va fi.', ['I’m cold. — I**’ll** close the window.', 'I think it **will** be clear.']],
    bank: [
      ['It’s cold. — I {} the window.', '’ll close', ['close', 'am close'], 'Hotărăști chiar acum: I’ll close.'],
      ['I think the sky {} be clear on Friday.', 'will', ['is going', 'is'], 'Părere despre viitor: will.'],
      ['Don’t worry. I {} tell anyone.', 'won’t', ['don’t', 'am not going'], 'Promisiune: I won’t tell.'],
      ['Maybe she {} come later.', 'will', ['is', 'comes'], 'Poate, în viitor: will.'],
      ['The phone is ringing. — I {} it!', '’ll get', ['get', 'am get'], 'Hotărâre pe loc: I’ll get it.'],
      ['I promise I {} you.', 'will help', ['help', 'am help'], 'Promisiune: will help.'],
    ] },
  'going-to': { ep: 9, title: 'going to',
    note: ['Going to pentru planuri hotărâte dinainte și pentru ce se vede că urmează.', ['We**’re going to** leave on Friday.', 'Look at those clouds! It**’s going to** rain.']],
    bank: [
      ['Look at those clouds! It {} rain.', '’s going to', ['going to', 'rains'], 'Se vede că urmează: it’s going to rain, cu is.'],
      ['We {} on Friday. It’s all planned.', '’re going to leave', ['going to leave', 'will to leave'], 'Plan hotărât: we’re going to leave, cu are.'],
      ['What {} you going to do tomorrow?', 'are', ['do', 'will'], 'Are you going to…?'],
      ['I’m going {} a new coat.', 'to buy', ['buy', 'buying'], 'Going to + verb.'],
      ['She {} going to come. She’s busy.', 'isn’t', ['doesn’t', 'won’t'], 'Negativ: isn’t going to.'],
      ['Careful! You {}!', '’re going to fall', ['will to fall', 'falling'], 'Se vede că urmează: you’re going to fall.'],
    ] },
  must: { ep: 10, title: 'must, have to, mustn’t, don’t have to',
    note: ['Must, have to: e obligatoriu. Mustn’t: e interzis. Don’t have to: nu e nevoie. După must și can nu vine „to”.', ['You **must** wear a helmet.', 'You **don’t have to** pay.']],
    bank: [
      ['It’s the rule: you {} wear a helmet on the roof.', 'must', ['must to', 'mustn’t'], 'Obligatoriu: must. Fără „to”.'],
      ['You {} smoke here. It’s not allowed.', 'mustn’t', ['don’t have to', 'must'], 'Interzis: mustn’t.'],
      ['It’s free. You {} pay.', 'don’t have to', ['mustn’t', 'haven’t'], 'Nu e nevoie: don’t have to.'],
      ['Visitors {} sign in at reception.', 'have to', ['has to', 'must to'], 'Obligatoriu: have to.'],
      ['She {} work on Saturdays.', 'has to', ['have to', 'must to'], 'She: has to.'],
      ['We {} be quiet in the library.', 'must', ['must to', 'have'], 'Obligatoriu: must.'],
    ] },
  can: { ep: 10, title: 'can, could, should',
    note: ['Can: poți. Could: puteai, sau o cerere politicoasă. Should: ar trebui (un sfat). După ele verbul e fără „to”.', ['**Can** you help us?', 'You **should** take a coat.']],
    bank: [
      ['{} you help me, please?', 'Could', ['Should', 'Must'], 'Cerere politicoasă: Could you…?'],
      ['I can {} English a little.', 'speak', ['to speak', 'speaking'], 'După can: fără „to”.'],
      ['It’s cold. You {} take a coat.', 'should', ['must to', 'can to'], 'Sfat: should.'],
      ['You {} use the lift. It’s broken.', 'can’t', ['mustn’t to', 'don’t can'], 'Nu se poate: can’t.'],
      ['When I was a child, I {} swim.', 'couldn’t', ['can’t', 'didn’t can'], 'Trecutul lui can: could.'],
      ['Can I {} your pen?', 'borrow', ['to borrow', 'lend'], 'Borrow = a lua cu împrumut. După can, fără „to”.'],
      ['You {} go to bed. It’s late.', 'should', ['should to', 'must to'], 'Sfat: should, fără „to”.'],
    ] },
  comp: { ep: 11, title: 'comparativul: -er, more',
    note: ['Cuvinte scurte: -er than (brighter than). Cuvinte lungi: more … than. Good → better, bad → worse.', ['It’s **brighter than** the moon.', 'It’s **more beautiful than** before.']],
    bank: [
      ['The lantern is {} than the moon.', 'brighter', ['more bright', 'brightest'], 'Cuvânt scurt: brighter.'],
      ['Tonight is {} than yesterday.', 'colder', ['more cold', 'coldest'], 'Cold → colder.'],
      ['This tea is {} than coffee.', 'better', ['gooder', 'more good'], 'Good → better.'],
      ['The office is {} than the shop.', 'taller', ['more tall', 'more taller'], 'Tall → taller.'],
      ['English is {} than I thought.', 'easier', ['more easy', 'easyer'], 'Easy → easier.'],
      ['This book is {} than that one.', 'more interesting', ['interestinger', 'most interesting'], 'Cuvânt lung: more interesting.'],
      ['The weather is {} today.', 'worse', ['badder', 'more bad'], 'Bad → worse.'],
    ] },
  sup: { ep: 11, title: 'superlativul: the -est, the most',
    note: ['Cel mai: the -est (the brightest), sau the most pentru cuvinte lungi. Good → the best.', ['It’s **the brightest** spark.', 'The **best** tea on the lane.']],
    bank: [
      ['This is the {} spark of all.', 'brightest', ['most bright', 'brighter'], 'Cuvânt scurt: the brightest.'],
      ['Tom makes the {} tea on Linden Lane.', 'best', ['goodest', 'most good'], 'Good → the best.'],
      ['It’s the {} night of the year.', 'darkest', ['most dark', 'darker'], 'Dark → the darkest.'],
      ['The office is the {} building on the lane.', 'tallest', ['most tall', 'taller'], 'Tall → the tallest.'],
      ['It was the {} day of my life.', 'most beautiful', ['beautifulest', 'more beautiful'], 'Cuvânt lung: the most beautiful.'],
      ['That was the {} film I’ve ever seen.', 'worst', ['baddest', 'most bad'], 'Bad → the worst.'],
    ] },
  if1: { ep: 12, title: 'if … will',
    note: ['Dacă se întâmplă ceva, urmează altceva: if + prezent, apoi will. După if nu vine will.', ['**If** the sky **is** clear, Aster **will** go home.']],
    bank: [
      ['If the sky {} clear, Aster will go home.', 'is', ['will be', 'was'], 'După if: prezent, nu will.'],
      ['If it rains, we {} wait.', 'will', ['are', 'would'], 'A doua parte: will.'],
      ['If you {} me, look at the tree.', 'miss', ['will miss', 'missed'], 'După if: prezent.'],
      ['I’ll call you if I {} late.', 'am', ['will be', 'be'], 'După if: prezent: if I am late.'],
      ['If you’re tired, you {} rest.', 'should', ['should to', 'must to'], 'Sfat, fără „to”.'],
      ['What will you do if she {} come?', 'doesn’t', ['won’t', 'don’t'], 'După if: prezent: doesn’t come.'],
      ['If we hurry, we {} the bus.', '’ll catch', ['catching', 'will catching'], 'A doua parte: will + verbul.'],
    ] },
};

export const POINTS = Object.keys(GRAMMAR);
export const pointsOf = ep => POINTS.filter(k => GRAMMAR[k].ep === ep);
