// The verb book: a page for every verb of the season, read at a glance. Opened by tapping a verb in the chat, in the
// episode's ending or in the verb album (screens/book.js). Romanian is kept short and marks English with `backticks`;
// English marks the verb with **x**.
//   s, ing: the he/she/it and -ing forms (past and past participle are in verbs.js)
//   means: [meaning, example] × 1–3 · tip: the one thing worth knowing (optional)
//   ex: [tense, English, Romanian] × 5 (tenses: TENSES in screens/book.js) · phrases: [English, Romanian]
//   traps: [wrong, right, why]: the mistakes Romanian speakers make

export const VERB_BOOK = {
  be: {
    s: 'am / is / are', ing: 'being',
    means: [['a fi', 'The tea **is** too hot.'], ['a se afla', 'Priya **is** in her shop.']],
    tip: 'Vârsta, foamea, frigul: cu `be`, nu `have`.',
    ex: [
      ['ps', 'Is Tom at the café today?', 'E Tom la cafenea azi?'],
      ['past', 'We were at home all evening.', 'Am fost acasă toată seara.'],
      ['pp', 'I’ve never been to Scotland.', 'N-am fost niciodată în Scoția.'],
      ['will', 'It’ll be cold tomorrow.', 'Mâine o să fie frig.'],
      ['imp', 'Don’t be late, please.', 'Te rog, nu întârzia.'],
    ],
    phrases: [['How are you?', 'Ce mai faci?'], ['I’m hungry.', 'Mi-e foame.'], ['Be careful!', 'Ai grijă.']],
    traps: [
      ['I have thirty years.', 'I’m thirty.', 'Vârsta: cu `be`.'],
      ['Where you are?', 'Where are you?', '`Are` trece înaintea lui `you`.'],
      ['Is very cold today.', 'It’s very cold today.', 'Lipsește subiectul: `it`.'],
    ],
  },

  have: {
    s: 'has', ing: 'having',
    means: [['a avea', 'I **have** two brothers.'], ['a mânca, a bea', 'We **have** lunch at one.']],
    tip: 'În vorbire: `I’ve got` = `I have`.',
    ex: [
      ['ps', 'Mrs Hughes has got a garden with roses.', 'Mrs Hughes are o grădină cu trandafiri.'],
      ['past', 'We had breakfast at Tom’s café.', 'Am luat micul dejun la cafeneaua lui Tom.'],
      ['pp', 'Have you had lunch yet?', 'Ai mâncat deja de prânz?'],
      ['can', 'Can I have a glass of water, please?', 'Îmi dați un pahar cu apă, vă rog?'],
      ['will', 'We won’t have time tomorrow.', 'Mâine n-o să avem timp.'],
    ],
    phrases: [['have breakfast', 'a lua micul dejun'], ['have a shower', 'a face duș'], ['have a good time', 'a se distra'], ['Have a good weekend!', 'Weekend plăcut.']],
    traps: [
      ['She have got a cat.', 'She has got a cat.', 'Cu `she`: `has got`.'],
      ['Do you have got a pen?', 'Have you got a pen?', 'Cu `got`, fără `do`.'],
      ['I make a shower every morning.', 'I have a shower every morning.', 'Dușul: `have a shower`.'],
    ],
  },

  look: {
    s: 'looks', ing: 'looking',
    means: [['a se uita', 'Mimi **looks at** the birds.'], ['a arăta (bine, rău)', 'This cake **looks** good.']],
    tip: 'Te uiți la ceva: `look at`. Cauți: `look for`.',
    ex: [
      ['ps', 'Tom looks tired today.', 'Tom arată obosit azi.'],
      ['pc', 'I’m looking for my keys.', 'Îmi caut cheile.'],
      ['past', 'She looked at the photo and smiled.', 'S-a uitat la poză și a zâmbit.'],
      ['pp', 'Have you looked in the kitchen?', 'Te-ai uitat în bucătărie?'],
      ['imp', 'Don’t look down.', 'Nu te uita în jos.'],
    ],
    phrases: [['look at', 'a se uita la'], ['look for', 'a căuta'], ['look after', 'a avea grijă de'], ['look like', 'a semăna cu']],
    traps: [
      ['Look this photo.', 'Look at this photo.', 'Lipsește `at`: `look at`.'],
      ['I’m looking after my keys.', 'I’m looking for my keys.', '`Look after` = a avea grijă de.'],
      ['You look like tired.', 'You look tired.', 'Înainte de adjectiv, fără `like`.'],
    ],
  },

  see: {
    s: 'sees', ing: 'seeing',
    means: [['a vedea', 'I can **see** the sea.'], ['a înțelege', 'Oh, I **see**.']],
    tip: 'Ce vezi acum: `I can see`, nu `I’m seeing`.',
    ex: [
      ['ps', 'Mimi sees everything from the window.', 'Mimi vede totul de la fereastră.'],
      ['can', 'I can’t see the moon tonight.', 'Nu văd luna în seara asta.'],
      ['past', 'I saw Tom at the café this morning.', 'L-am văzut pe Tom la cafenea azi-dimineață.'],
      ['pp', 'Have you seen my keys?', 'Mi-ai văzut cheile?'],
      ['will', 'You’ll see the shop on your left.', 'O să vezi magazinul pe stânga.'],
    ],
    phrases: [['I see.', 'Înțeleg.'], ['See you later!', 'Ne vedem mai târziu.'], ['Let’s see.', 'Să vedem.']],
    traps: [
      ['I am seeing the moon.', 'I can see the moon.', 'Acum: `can see`.'],
      ['I saw at the picture.', 'I looked at the picture.', 'Te uiți la ceva: `look at`.'],
      ['I have saw this film.', 'I have seen this film.', 'După `have`: `seen`.'],
    ],
  },

  open: {
    s: 'opens', ing: 'opening',
    means: [['a deschide', 'Mimi can’t **open** the door.'], ['a se deschide', 'Priya’s shop **opens** at eight.']],
    tip: 'Lumina, televizorul: `turn on`, nu `open`.',
    ex: [
      ['ps', 'What time does the shop open?', 'La ce oră se deschide magazinul?'],
      ['past', 'Priya opened her shop ten years ago.', 'Priya și-a deschis magazinul acum zece ani.'],
      ['pp', 'I haven’t opened the letter yet.', 'Încă n-am deschis scrisoarea.'],
      ['imp', 'Open the window, please. It’s hot in here.', 'Deschide fereastra, te rog. E cald aici.'],
      ['can', 'I can’t open this jar.', 'Nu pot să deschid borcanul ăsta.'],
    ],
    phrases: [['The shop is open.', 'Magazinul e deschis.'], ['open a bank account', 'a deschide un cont în bancă'], ['open a present', 'a desface un cadou']],
    traps: [
      ['Can you open the light?', 'Can you turn on the light?', 'Lumina se aprinde: `turn on`.'],
      ['The shop is opened now.', 'The shop is open now.', '„E deschis”: `is open`.'],
    ],
  },

  help: {
    s: 'helps', ing: 'helping',
    means: [['a ajuta', 'Can you **help** me **with** the bags?']],
    tip: 'Fără prepoziție: `help me`. La ceva: `help with`.',
    ex: [
      ['ps', 'My sister often helps me with my English.', 'Sora mea mă ajută des la engleză.'],
      ['past', 'You helped me a lot yesterday. Thank you.', 'M-ai ajutat mult ieri. Mulțumesc.'],
      ['pp', 'Has the medicine helped?', 'Te-a ajutat medicamentul?'],
      ['can', 'Sorry, I can’t help you today.', 'Îmi pare rău, azi nu te pot ajuta.'],
      ['will', 'Don’t worry. I’ll help you.', 'Nu-ți face griji. Te ajut eu.'],
    ],
    phrases: [['Can I help you?', 'Cu ce vă pot ajuta?'], ['Help yourself.', 'Servește-te.'], ['I can’t help it.', 'Nu mă pot abține.']],
    traps: [
      ['Can you help me at my homework?', 'Can you help me with my homework?', 'La ceva: `help with`, nu `at`.'],
      ['Can you help to me?', 'Can you help me?', 'Fără `to`: `help me`.'],
      ['Wait, I help you.', 'Wait, I’ll help you.', 'Te oferi acum: `I’ll help`.'],
    ],
  },

  drink: {
    s: 'drinks', ing: 'drinking',
    means: [['a bea', 'Sam **drinks** a lot of coffee.'], ['a bea alcool', 'No wine for me. I don’t **drink**.']],
    tip: 'Când comanzi: `I’ll have a coffee, please`.',
    ex: [
      ['ps', 'I don’t drink coffee in the evening.', 'Seara nu beau cafea.'],
      ['pc', 'Mimi is drinking from my glass again.', 'Mimi bea iar din paharul meu.'],
      ['past', 'We drank tea in the garden.', 'Am băut ceai în grădină.'],
      ['pp', 'Who has drunk all the milk?', 'Cine a băut tot laptele?'],
      ['can', 'You should drink more water.', 'Ar trebui să bei mai multă apă.'],
    ],
    phrases: [['something to drink', 'ceva de băut'], ['go for a drink', 'a ieși la un pahar'], ['Drink up.', 'Bea tot.']],
    traps: [
      ['I drinked all the milk.', 'I drank all the milk.', '`Drink` e neregulat: `drank`.'],
      ['I have drank the tea.', 'I have drunk the tea.', 'După `have`: `drunk`.'],
      ['I drink a pill every morning.', 'I take a pill every morning.', 'Pastilele se iau: `take`.'],
    ],
  },

  like: {
    s: 'likes', ing: 'liking',
    means: [['a-i plăcea', 'I **like** your coat.'], ['a vrea (politicos)', 'I**’d like** two tickets, please.']],
    tip: '„Îmi place cafeaua” = `I like coffee`.',
    ex: [
      ['ps', 'My brother doesn’t like cats.', 'Fratelui meu nu-i plac pisicile.'],
      ['past', 'Did you like the film?', 'Ți-a plăcut filmul?'],
      ['pp', 'I’ve always liked rainy days.', 'Mi-au plăcut mereu zilele ploioase.'],
      ['will', 'You’ll like Tom. He’s very kind.', 'O să-ți placă Tom. E foarte amabil.'],
      ['going', 'Mimi isn’t going to like this.', 'Lui Mimi n-o să-i placă asta.'],
    ],
    phrases: [['Would you like some tea?', 'Vrei niște ceai?'], ['I’d like a coffee, please.', 'Aș vrea o cafea, vă rog.'], ['I like it here.', 'Îmi place aici.']],
    traps: [
      ['I like very much tea.', 'I like tea very much.', '`Very much` vine la sfârșit.'],
      ['Do you like?', 'Do you like it?', 'Lipsește complementul: `it`.'],
      ['She doesn’t likes milk.', 'She doesn’t like milk.', 'După `doesn’t`, fără `-s`.'],
    ],
  },

  want: {
    s: 'wants', ing: 'wanting',
    means: [['a vrea', 'Mimi **wants** her dinner.']],
    tip: '„Vreau să stai” = `I want you to stay`.',
    ex: [
      ['ps', 'What do you want for dinner?', 'Ce vrei la cină?'],
      ['past', 'Sorry, I didn’t want to wake you.', 'Scuze, n-am vrut să te trezesc.'],
      ['pp', 'I’ve always wanted a dog.', 'Mereu mi-am dorit un câine.'],
      ['will', 'Tom will want to see this.', 'Tom o să vrea să vadă asta.'],
      ['going', 'The children are going to want ice cream.', 'Copiii o să vrea înghețată.'],
    ],
    phrases: [['if you want', 'dacă vrei'], ['Do you want a lift?', 'Vrei să te duc cu mașina?'], ['I just wanted to say thank you.', 'Voiam doar să-ți mulțumesc.']],
    traps: [
      ['I want that you stay.', 'I want you to stay.', 'Fără `that`: `want you to`.'],
      ['I want go home.', 'I want to go home.', 'Cu alt verb: `want to`.'],
      ['No, I don’t want.', 'No, I don’t want to.', '`To` rămâne, chiar fără verb.'],
    ],
  },

  need: {
    s: 'needs', ing: 'needing',
    means: [['a avea nevoie de', 'I **need** a new phone.'], ['a trebui (să)', 'We **need to** leave at six.']],
    tip: '„Am nevoie de” = `need`, fără `of`.',
    ex: [
      ['ps', 'Do you need anything from the shop?', 'Ai nevoie de ceva de la magazin?'],
      ['past', 'We needed help, so I called Tom.', 'Aveam nevoie de ajutor, așa că l-am sunat pe Tom.'],
      ['pp', 'I’ve never needed a car here.', 'N-am avut niciodată nevoie de mașină aici.'],
      ['will', 'You’ll need an umbrella today.', 'Azi o să ai nevoie de umbrelă.'],
      ['going', 'We’re going to need more chairs.', 'O să avem nevoie de mai multe scaune.'],
    ],
    phrases: [['You don’t need to.', 'Nu e nevoie.'], ['I need a break.', 'Am nevoie de o pauză.'], ['if you need anything', 'dacă ai nevoie de ceva']],
    traps: [
      ['I have need of a pen.', 'I need a pen.', 'Un singur verb: `need`.'],
      ['I need go now.', 'I need to go now.', 'Cu alt verb: `need to`.'],
    ],
  },

  work: {
    s: 'works', ing: 'working',
    means: [['a lucra', 'My sister **works** in a hospital.'], ['a merge, a funcționa', 'The heating doesn’t **work**.']],
    tip: 'Meseria: `work as`. Firma: `work for`.',
    ex: [
      ['ps', 'Priya works six days a week.', 'Priya lucrează șase zile pe săptămână.'],
      ['pc', 'My phone isn’t working again.', 'Iar nu-mi merge telefonul.'],
      ['past', 'Did you work late yesterday?', 'Ai lucrat până târziu ieri?'],
      ['pp', 'Dr Okafor has worked in that office for years.', 'Dr Okafor lucrează în biroul acela de ani de zile.'],
      ['will', 'I’ll work from home tomorrow.', 'Mâine lucrez de acasă.'],
    ],
    phrases: [['go to work', 'a merge la serviciu'], ['at work', 'la serviciu'], ['work hard', 'a munci din greu'], ['It doesn’t work.', 'Nu merge.']],
    traps: [
      ['I work like a teacher.', 'I work as a teacher.', 'Meseria: `work as`, nu `like`.'],
      ['I go to the work at eight.', 'I go to work at eight.', 'Fără `the`: `go to work`.'],
      ['The lift doesn’t function.', 'The lift doesn’t work.', 'Aparatele: `work`, nu `function`.'],
    ],
  },

  make: {
    s: 'makes', ing: 'making',
    means: [['a face, a prepara', 'Tom **makes** very good tea.'], ['a produce, a construi', 'They **make** cars here.']],
    tip: 'Ceai, prăjituri, greșeli: `make`. Teme, treburi: `do`.',
    ex: [
      ['ps', 'Who makes the coffee in your office?', 'Cine face cafeaua la voi la birou?'],
      ['pc', 'I’m making a cake for Sunday.', 'Fac un tort pentru duminică.'],
      ['past', 'Sorry, I made a mistake.', 'Scuze, am greșit.'],
      ['pp', 'Tom has made tea for everyone.', 'Tom a făcut ceai pentru toată lumea.'],
      ['imp', 'Don’t make a noise. Mimi is sleeping.', 'Nu face zgomot. Mimi doarme.'],
    ],
    phrases: [['make a mistake', 'a greși'], ['make friends', 'a-și face prieteni'], ['make a decision', 'a lua o hotărâre'], ['make a phone call', 'a da un telefon']],
    traps: [
      ['I make my homework.', 'I do my homework.', 'Temele: `do`.'],
      ['I made a photo.', 'I took a photo.', 'Pozele: `take`.'],
      ['How much does it make?', 'How much is it?', '„Cât face?” = `How much is it?`'],
    ],
  },

  do: {
    s: 'does', ing: 'doing',
    means: [['a face', 'What are you **doing**?'], ['în întrebări și negații', '**Do** you like tea? — No, I **don’t**.']],
    tip: 'Teme, treburi: `do`. Greșeli: `make`.',
    ex: [
      ['ps', 'What do you do on Sundays?', 'Ce faci duminica?'],
      ['pc', 'I’m doing the washing-up.', 'Spăl vasele.'],
      ['past', 'I didn’t do much yesterday.', 'Ieri n-am făcut mare lucru.'],
      ['pp', 'Have you done your homework?', 'Ți-ai făcut temele?'],
      ['will', 'I’ll do the shopping tomorrow.', 'Mâine fac eu cumpărăturile.'],
    ],
    phrases: [['What do you do?', 'Cu ce te ocupi?'], ['do the cleaning', 'a face curat'], ['do your best', 'a face tot ce poți'], ['do some exercise', 'a face mișcare']],
    traps: [
      ['Where you work?', 'Where do you work?', 'Întrebarea, la prezent: cu `do`.'],
      ['Does she works here?', 'Does she work here?', 'După `does`, fără `-s`.'],
      ['I did a mistake.', 'I made a mistake.', 'Greșeala: `make a mistake`.'],
    ],
  },

  try: {
    s: 'tries', ing: 'trying',
    means: [['a încerca', 'Please **try to** come early.'], ['a gusta', '**Try** Tom’s carrot cake.']],
    tip: 'Hainele se probează: `try on`.',
    ex: [
      ['ps', 'Mimi tries to catch birds every day.', 'Mimi încearcă în fiecare zi să prindă păsări.'],
      ['pc', 'I’m trying to sleep. Please be quiet.', 'Încerc să dorm. Te rog, fă liniște.'],
      ['past', 'I tried to call you twice.', 'Am încercat de două ori să te sun.'],
      ['pp', 'Have you ever tried Indian food?', 'Ai gustat vreodată mâncare indiană?'],
      ['imp', 'Don’t try to fix it yourself.', 'Nu încerca să-l repari tu.'],
    ],
    phrases: [['try on', 'a proba (haine)'], ['Try again.', 'Mai încearcă.'], ['try hard', 'a se strădui']],
    traps: [
      ['I tryed to call you.', 'I tried to call you.', 'Consoană + `y`: `tried`.'],
      ['I try to come tomorrow.', 'I’ll try to come tomorrow.', 'Pentru viitor: `I’ll try`.'],
      ['Try to don’t worry.', 'Try not to worry.', 'Negația: `try not to`.'],
    ],
  },

  fix: {
    s: 'fixes', ing: 'fixing',
    means: [['a repara', 'Can you **fix** my chair?'], ['a rezolva', 'We can **fix** this problem.']],
    tip: 'În vorbire, mai des decât `repair`.',
    ex: [
      ['ps', 'My dad fixes everything in the house.', 'Tata repară tot prin casă.'],
      ['pc', 'Tom is fixing the coffee machine.', 'Tom repară aparatul de cafea.'],
      ['past', 'Who fixed your bike?', 'Cine ți-a reparat bicicleta?'],
      ['pp', 'They haven’t fixed the lift yet.', 'Încă n-au reparat liftul.'],
      ['will', 'Leave it. I’ll fix it.', 'Lasă, îl repar eu.'],
    ],
    phrases: [['fix a problem', 'a rezolva o problemă'], ['get something fixed', 'a da ceva la reparat'], ['It’s easy to fix.', 'Se repară ușor.']],
    traps: [
      ['I fixed my phone at a shop.', 'I got my phone fixed at a shop.', 'Dacă repară altcineva: `get it fixed`.'],
      ['He fixs bikes in his garage.', 'He fixes bikes in his garage.', 'După `x`, cu `-es`: `fixes`.'],
    ],
  },

  build: {
    s: 'builds', ing: 'building',
    means: [['a construi', 'Who **built** this wall?']],
    tip: 'Clădirile, des la pasiv: `was built`.',
    ex: [
      ['ps', 'Birds build their nests in spring.', 'Păsările își fac cuiburi primăvara.'],
      ['pc', 'They’re building a new school near us.', 'Construiesc o școală nouă lângă noi.'],
      ['past', 'When was this house built?', 'Când a fost construită casa asta?'],
      ['pp', 'They still haven’t built the new bridge.', 'Încă n-au construit podul cel nou.'],
      ['going', 'We’re going to build a shed in the garden.', 'O să facem o magazie în grădină.'],
    ],
    phrases: [['build a snowman', 'a face un om de zăpadă'], ['build a sandcastle', 'a face un castel de nisip'], ['build a fire', 'a face un foc']],
    traps: [
      ['My grandfather builded this house.', 'My grandfather built this house.', '`Build` e neregulat: `built`.'],
      ['This house was build in 1900.', 'This house was built in 1900.', 'După `was`: `built`.'],
      ['We made a house in the village.', 'We built a house in the village.', 'Casa se construiește: `build`.'],
    ],
  },

  watch: {
    s: 'watches', ing: 'watching',
    means: [['a privi, a urmări', 'Sam **watches** football on Sundays.'], ['a avea grijă de', 'Can you **watch** the children tonight?']],
    tip: 'Film, meci: `watch`. Poză: `look at`.',
    ex: [
      ['ps', 'Do you watch the news every evening?', 'Te uiți la știri în fiecare seară?'],
      ['pc', 'Mimi is watching the rain.', 'Mimi se uită la ploaie.'],
      ['past', 'We watched a film last night.', 'Aseară ne-am uitat la un film.'],
      ['pp', 'I haven’t watched TV for weeks.', 'Nu m-am mai uitat la televizor de câteva săptămâni.'],
      ['can', 'Can you watch my bag for a minute?', 'Îmi păzești geanta un minut?'],
    ],
    phrases: [['watch TV', 'a se uita la televizor'], ['Watch out!', 'Ai grijă.'], ['Watch your step.', 'Ai grijă pe unde calci.']],
    traps: [
      ['I watched the photo.', 'I looked at the photo.', 'Poza stă pe loc: `look at`.'],
      ['We watched at TV all evening.', 'We watched TV all evening.', 'Fără prepoziție: `watch TV`.'],
      ['I looked at a film last night.', 'I watched a film last night.', 'Un film îl urmărești: `watch`.'],
    ],
  },

  carry: {
    s: 'carries', ing: 'carrying',
    means: [['a căra, a duce', 'Let me **carry** your bag.'], ['a avea la tine', 'I never **carry** much money.']],
    tip: 'Haine, ochelari: `wear`, nu `carry`.',
    ex: [
      ['ps', 'I always carry a book in my bag.', 'Am mereu o carte în geantă.'],
      ['pc', 'Why are you carrying an umbrella? It’s sunny.', 'De ce ai umbrelă la tine? E soare.'],
      ['past', 'My dad carried me on his shoulders.', 'Tata mă purta pe umeri.'],
      ['pp', 'Has anyone carried the chairs inside?', 'A dus cineva scaunele înăuntru?'],
      ['can', 'This box is too heavy. I can’t carry it.', 'Cutia asta e prea grea. Nu pot s-o car.'],
    ],
    phrases: [['carry on', 'a continua'], ['carry a baby', 'a ține un copil în brațe'], ['carry the shopping', 'a căra cumpărăturile']],
    traps: [
      ['I carry glasses.', 'I wear glasses.', 'Ochelarii se poartă: `wear`.'],
      ['He carrys the bags.', 'He carries the bags.', 'Consoană + `y`: `carries`.'],
    ],
  },

  happen: {
    s: 'happens', ing: 'happening',
    means: [['a se întâmpla', 'It all **happened** very quickly.']],
    tip: 'Cui i se întâmplă: `happen to`, nu `with`.',
    ex: [
      ['ps', 'It happens to everyone.', 'I se întâmplă oricui.'],
      ['pc', 'What’s happening in the street?', 'Ce se întâmplă pe stradă?'],
      ['past', 'What happened to your phone?', 'Ce s-a întâmplat cu telefonul tău?'],
      ['pp', 'This has never happened to me before.', 'Nu mi s-a mai întâmplat niciodată.'],
      ['will', 'Sorry. It won’t happen again.', 'Îmi pare rău. Nu se va mai întâmpla.'],
    ],
    phrases: [['What happened?', 'Ce s-a întâmplat?'], ['What happened to you?', 'Ce ți s-a întâmplat?'], ['These things happen.', 'Se mai întâmplă.']],
    traps: [
      ['It was happened yesterday.', 'It happened yesterday.', 'Nu are pasiv: doar `happened`.'],
      ['What happened with you?', 'What happened to you?', 'Cuiva: `happen to`, nu `with`.'],
      ['What did happen?', 'What happened?', '`What` e subiect: fără `did`.'],
    ],
  },
  stop: {
    s: 'stops', ing: 'stopping',
    means: [['a (se) opri', 'Sam **stops** the bus by the café.'], ['a nu mai face', 'The baby **stopped** crying.']],
    tip: 'Nu mai faci ceva: `stop` + `-ing`.',
    ex: [
      ['ps', 'Does this bus stop near the station?', 'Autobuzul ăsta oprește lângă gară?'],
      ['imp', 'Please stop talking and listen.', 'Vă rog, nu mai vorbiți și ascultați.'],
      ['past', 'The car stopped in front of the house.', 'Mașina s-a oprit în fața casei.'],
      ['pp', 'It has stopped raining.', 'S-a oprit ploaia.'],
      ['can', 'I can’t stop thinking about it.', 'Nu pot să nu mă gândesc la asta.'],
    ],
    phrases: [['Stop it!', 'Încetează.'], ['stop smoking', 'a se lăsa de fumat'], ['stop for a coffee', 'a se opri la o cafea']],
    traps: [
      ['I stopped to smoke last year.', 'I stopped smoking last year.', 'Te lași de ceva: `-ing`.'],
      ['Can you stop the TV?', 'Can you turn off the TV?', 'Aparatele: `turn off`.'],
      ['The bus stoped at the corner.', 'The bus stopped at the corner.', 'Se dublează `p`: `stopped`.'],
    ],
  },
  arrive: {
    s: 'arrives', ing: 'arriving',
    means: [['a sosi, a ajunge', 'We **arrived** in London at night.']],
    tip: 'Oraș, țară: `in`. Gară, hotel: `at`. Nu `to`.',
    ex: [
      ['ps', 'The train arrives at ten past six.', 'Trenul sosește la șase și zece.'],
      ['pc', 'Hurry up, the guests are arriving.', 'Grăbește-te, sosesc musafirii.'],
      ['past', 'What time did you arrive?', 'La ce oră ai ajuns?'],
      ['pp', 'Your parcel has arrived.', 'Ți-a sosit coletul.'],
      ['will', 'The letter won’t arrive before Monday.', 'Scrisoarea nu ajunge înainte de luni.'],
    ],
    phrases: [['arrive home', 'a ajunge acasă'], ['arrive on time', 'a ajunge la timp'], ['arrive at work', 'a ajunge la serviciu']],
    traps: [
      ['We arrived to the hotel at nine.', 'We arrived at the hotel at nine.', 'La hotel: `at`, nu `to`.'],
      ['We arrived at Paris on Monday.', 'We arrived in Paris on Monday.', 'Orașe și țări: `in`.'],
      ['We arrived to home late.', 'We arrived home late.', 'Cu `home`: fără prepoziție.'],
    ],
  },
  walk: {
    s: 'walks', ing: 'walking',
    means: [['a merge pe jos', 'Let’s **walk**. It’s not far.'], ['a plimba', 'I **walk** the dog every morning.']],
    tip: 'Spre un loc: `walk to`. Acasă: `walk home`.',
    ex: [
      ['ps', 'I walk to work every day.', 'Merg pe jos la serviciu în fiecare zi.'],
      ['pc', 'I’m not walking in this rain.', 'Nu merg pe jos pe ploaia asta.'],
      ['past', 'We walked home after the film.', 'După film, ne-am întors acasă pe jos.'],
      ['pp', 'I’ve walked ten kilometres today.', 'Azi am mers zece kilometri pe jos.'],
      ['can', 'Can we walk there, or is it too far?', 'Putem merge pe jos până acolo sau e prea departe?'],
    ],
    phrases: [['go for a walk', 'a ieși la plimbare'], ['walk the dog', 'a plimba câinele'], ['walk to school', 'a merge pe jos la școală']],
    traps: [
      ['We walked to home.', 'We walked home.', 'Cu `home`: fără `to`.'],
      ['Let’s make a walk.', 'Let’s go for a walk.', 'Plimbarea: `go for a walk`.'],
    ],
  },
  call: {
    s: 'calls', ing: 'calling',
    means: [['a suna', 'Tom **called** me this morning.'], ['a chema', '**Call** the children for dinner.'], ['a numi', 'We **call** the cat Mimi.']],
    tip: 'Suni pe cineva: `call Tom`, fără `to`.',
    ex: [
      ['ps', 'My mum calls me every Sunday.', 'Mama mă sună în fiecare duminică.'],
      ['past', 'I called you twice yesterday.', 'Te-am sunat de două ori ieri.'],
      ['pp', 'Has anyone called the doctor?', 'A chemat cineva doctorul?'],
      ['will', 'I’ll call you tonight.', 'Te sun diseară.'],
      ['imp', 'Please don’t call after ten.', 'Te rog, nu suna după ora zece.'],
    ],
    phrases: [['call someone back', 'a suna pe cineva înapoi'], ['call a taxi', 'a chema un taxi'], ['What’s it called?', 'Cum se numește?']],
    traps: [
      ['I called to Tom yesterday.', 'I called Tom yesterday.', 'Fără `to`: `call Tom`.'],
      ['How do you call this in English?', 'What do you call this in English?', '„Cum îi spui?”: `What`, nu `How`.'],
    ],
  },
  stay: {
    s: 'stays', ing: 'staying',
    means: [['a rămâne', 'Can you **stay** for dinner?'], ['a sta (o vreme)', 'We’re **staying** at a small hotel.']],
    tip: 'A sta jos e `sit`. A locui e `live`.',
    ex: [
      ['ps', 'We usually stay with my aunt in summer.', 'Vara stăm de obicei la mătușa mea.'],
      ['past', 'I stayed at home all weekend.', 'Am stat acasă tot weekendul.'],
      ['pp', 'Have you ever stayed in a hotel by the sea?', 'Ai stat vreodată la un hotel la mare?'],
      ['going', 'I’m not going to stay long.', 'N-o să stau mult.'],
      ['imp', 'Stay here. I’ll be back in a minute.', 'Rămâi aici. Mă întorc imediat.'],
    ],
    phrases: [['stay in bed', 'a sta în pat'], ['stay up late', 'a sta treaz până târziu'], ['stay in touch', 'a păstra legătura']],
    traps: [
      ['I stay in London with my family.', 'I live in London with my family.', 'Unde locuiești: `live`.'],
      ['Stay down, please.', 'Sit down, please.', '„Stai jos”: `sit down`.'],
    ],
  },
  buy: {
    s: 'buys', ing: 'buying',
    means: [['a cumpăra', 'Tom **bought** a new coffee machine.']],
    tip: '`Bought` = cumpărat. `Brought` = adus.',
    ex: [
      ['ps', 'I buy bread at Priya’s shop.', 'Cumpăr pâine de la magazinul lui Priya.'],
      ['past', 'I bought a new coat last week.', 'Mi-am cumpărat o haină nouă săptămâna trecută.'],
      ['pp', 'Have you bought the tickets yet?', 'Ai cumpărat deja biletele?'],
      ['going', 'We’re going to buy a flat next year.', 'Anul viitor o să ne cumpărăm un apartament.'],
      ['can', 'I can’t buy it. It’s too expensive.', 'Nu pot să-l cumpăr. E prea scump.'],
    ],
    phrases: [['buy a ticket', 'a cumpăra un bilet'], ['buy someone a present', 'a-i cumpăra cuiva un cadou'], ['buy something online', 'a cumpăra ceva online']],
    traps: [
      ['I buyed a jacket.', 'I bought a jacket.', 'Trecutul: `bought`.'],
      ['I bought for my sister a present.', 'I bought my sister a present.', 'Întâi persoana, apoi lucrul.'],
      ['I brought it for ten pounds.', 'I bought it for ten pounds.', 'Cumpărat: `bought`, nu `brought`.'],
    ],
  },
  sell: {
    s: 'sells', ing: 'selling',
    means: [['a vinde', 'Priya **sells** bread and milk.']],
    tip: 'Prețul vine cu `for`: `for ten pounds`.',
    ex: [
      ['ps', 'The shop on the corner doesn’t sell stamps.', 'Magazinul din colț nu vinde timbre.'],
      ['pc', 'Our neighbours are selling their house.', 'Vecinii noștri își vând casa.'],
      ['past', 'I sold my old bike last month.', 'Mi-am vândut bicicleta veche luna trecută.'],
      ['pp', 'Have they sold all the tickets?', 'Au vândut toate biletele?'],
      ['will', 'I’ll sell you my old phone for twenty pounds.', 'Îți vând telefonul meu vechi cu douăzeci de lire.'],
    ],
    phrases: [['for sale', 'de vânzare'], ['sold out', 'epuizat, s-a vândut tot'], ['sell well', 'a se vinde bine']],
    traps: [
      ['I selled my car.', 'I sold my car.', 'Trecutul: `sold`.'],
      ['I sold my bike with fifty pounds.', 'I sold my bike for fifty pounds.', 'Prețul: `for`, nu `with`.'],
      ['She sold to me a lamp.', 'She sold me a lamp.', 'Persoana după verb: fără `to`.'],
    ],
  },
  cost: {
    s: 'costs', ing: 'costing',
    means: [['a costa', 'A coffee **costs** two pounds at Tom’s.']],
    tip: 'Întrebi prețul: `How much is it?`',
    ex: [
      ['ps', 'How much does this lamp cost?', 'Cât costă lampa asta?'],
      ['past', 'My new phone cost a lot of money.', 'Telefonul meu nou a costat mulți bani.'],
      ['pp', 'This trip has cost us a fortune.', 'Excursia asta ne-a costat o avere.'],
      ['will', 'It won’t cost much to fix.', 'Reparația n-o să coste mult.'],
      ['can', 'A taxi to the airport can cost fifty pounds.', 'Un taxi până la aeroport poate costa cincizeci de lire.'],
    ],
    phrases: [['How much is it?', 'Cât costă?'], ['cost a lot', 'a costa mult'], ['It doesn’t cost anything.', 'Nu costă nimic.']],
    traps: [
      ['How much it costs?', 'How much does it cost?', 'Întrebarea: cu `does`, fără `-s`.'],
      ['It costed ten pounds.', 'It cost ten pounds.', 'Trecutul: tot `cost`.'],
      ['This coat costs very expensive.', 'This coat is very expensive.', '„Costă scump”: `is expensive`.'],
    ],
  },
  pay: {
    s: 'pays', ing: 'paying',
    means: [['a plăti', 'I’ll **pay** for the tickets.']],
    tip: 'Ce cumperi: `pay for`. Nota, chiria: doar `pay`.',
    ex: [
      ['ps', 'I usually pay by card.', 'De obicei plătesc cu cardul.'],
      ['past', 'Who paid for the coffee?', 'Cine a plătit cafeaua?'],
      ['pp', 'I haven’t paid the rent yet.', 'Încă n-am plătit chiria.'],
      ['can', 'Can I pay in cash?', 'Pot să plătesc în numerar?'],
      ['will', 'Put your money away. I’ll pay.', 'Lasă banii. Plătesc eu.'],
    ],
    phrases: [['pay the bill', 'a plăti nota'], ['pay attention', 'a fi atent'], ['pay someone back', 'a-i da cuiva banii înapoi']],
    traps: [
      ['I paid the coffee.', 'I paid for the coffee.', 'Ce cumperi: `pay for`.'],
      ['I payed ten pounds.', 'I paid ten pounds.', 'Se scrie `paid`.'],
    ],
  },
  find: {
    s: 'finds', ing: 'finding',
    means: [['a găsi', 'I **found** a nice café near the station.']],
    tip: 'Cauți: `look for`. Ai găsit: `find`.',
    ex: [
      ['ps', 'Mimi always finds the warmest place in the house.', 'Mimi găsește mereu cel mai cald loc din casă.'],
      ['past', 'I found some money in my old coat.', 'Am găsit niște bani în haina veche.'],
      ['pp', 'Have you found a new job?', 'Ți-ai găsit o slujbă nouă?'],
      ['can', 'I can’t find my phone anywhere.', 'Nu-mi găsesc telefonul nicăieri.'],
      ['will', 'We’ll find a good flat soon.', 'O să găsim curând un apartament bun.'],
    ],
    phrases: [['find out', 'a afla'], ['find the way', 'a găsi drumul'], ['find time', 'a-și face timp']],
    traps: [
      ['I’m finding my keys.', 'I’m looking for my keys.', 'Cât timp cauți: `look for`.'],
      ['I finded it under the bed.', 'I found it under the bed.', 'Trecutul: `found`.'],
    ],
  },
  bring: {
    s: 'brings', ing: 'bringing',
    means: [['a aduce', 'Tom **brought** us some tea.']],
    tip: 'Spre tine: `bring`. Spre alt loc: `take`.',
    ex: [
      ['ps', 'The postman brings the letters at ten.', 'Poștașul aduce scrisorile la zece.'],
      ['past', 'My sister brought a cake to the party.', 'Sora mea a adus un tort la petrecere.'],
      ['pp', 'I haven’t brought an umbrella.', 'Nu mi-am luat umbrelă.'],
      ['can', 'Can you bring me a glass of water?', 'Îmi poți aduce un pahar cu apă?'],
      ['will', 'I’ll bring the photos tomorrow.', 'Aduc pozele mâine.'],
    ],
    phrases: [['bring something back', 'a aduce ceva înapoi'], ['bring a friend', 'a veni cu un prieten'], ['bring someone something', 'a-i aduce cuiva ceva']],
    traps: [
      ['Can you bring this letter to the post office?', 'Can you take this letter to the post office?', 'Spre alt loc: `take`.'],
      ['She bringed some flowers.', 'She brought some flowers.', 'Trecutul: `brought`.'],
      ['I bought my laptop to work.', 'I brought my laptop to work.', 'Adus: `brought`, nu `bought`.'],
    ],
  },
  put: {
    s: 'puts', ing: 'putting',
    means: [['a pune', '**Put** the cups on the table.']],
    tip: 'După `put` vine și locul: `put it here`.',
    ex: [
      ['ps', 'I always put sugar in my tea.', 'Pun mereu zahăr în ceai.'],
      ['pc', 'Tom is putting the chairs outside.', 'Tom scoate scaunele afară.'],
      ['past', 'Where did you put the scissors?', 'Unde ai pus foarfeca?'],
      ['pp', 'I’ve put the milk in the fridge.', 'Am pus laptele în frigider.'],
      ['imp', 'Don’t put your feet on the sofa.', 'Nu pune picioarele pe canapea.'],
    ],
    phrases: [['put on a coat', 'a-și pune o haină'], ['put away', 'a pune la loc'], ['put the kettle on', 'a pune apa la fiert']],
    traps: [
      ['I putted the book on the shelf.', 'I put the book on the shelf.', 'Trecutul: tot `put`.'],
      ['Put your coat. It’s cold.', 'Put your coat on. It’s cold.', 'Hainele: `put on`.'],
    ],
  },
  leave: {
    s: 'leaves', ing: 'leaving',
    means: [['a pleca', 'Tom **left** the café at ten.'], ['a lăsa', '**Leave** your coat by the door.']],
    tip: 'Ai uitat ceva undeva: `leave`, nu `forget`.',
    ex: [
      ['ps', 'My train leaves at half past seven.', 'Trenul meu pleacă la șapte și jumătate.'],
      ['pc', 'Are you leaving already?', 'Pleci deja?'],
      ['past', 'I left my umbrella on the bus.', 'Mi-am uitat umbrela în autobuz.'],
      ['pp', 'Dr Okafor has just left the office.', 'Dr Okafor tocmai a plecat de la birou.'],
      ['imp', 'Don’t leave the door open.', 'Nu lăsa ușa deschisă.'],
    ],
    phrases: [['leave a message', 'a lăsa un mesaj'], ['leave someone alone', 'a lăsa pe cineva în pace'], ['leave for work', 'a pleca la serviciu']],
    traps: [
      ['I forgot my keys at home.', 'I left my keys at home.', 'Cu locul: `leave`, nu `forget`.'],
      ['Leave me to pay.', 'Let me pay.', '„Lasă-mă să…”: `let me`.'],
      ['We’re leaving to Paris on Friday.', 'We’re leaving for Paris on Friday.', 'Spre un loc: `leave for`.'],
    ],
  },
  hide: {
    s: 'hides', ing: 'hiding',
    means: [['a ascunde', 'He **hid** the letter in a drawer.'], ['a se ascunde', 'Mimi is **hiding** behind the sofa.']],
    tip: 'Te ascunzi de cineva: `hide from`.',
    ex: [
      ['ps', 'Mimi hides under the bed when there’s a storm.', 'Mimi se ascunde sub pat când e furtună.'],
      ['pc', 'Why are you hiding behind the door?', 'De ce te ascunzi după ușă?'],
      ['past', 'I hid the presents in the wardrobe.', 'Am ascuns cadourile în șifonier.'],
      ['pp', 'I haven’t hidden anything from you.', 'Nu ți-am ascuns nimic.'],
      ['imp', 'Hide the chocolate before the children see it.', 'Ascunde ciocolata până n-o văd copiii.'],
    ],
    phrases: [['hide from someone', 'a se ascunde de cineva'], ['hide something from someone', 'a ascunde ceva de cineva'], ['play hide-and-seek', 'a se juca de-a v-ați ascunselea']],
    traps: [
      ['I hided the key.', 'I hid the key.', 'Trecutul: `hid`.'],
      ['Where have you hid the money?', 'Where have you hidden the money?', 'După `have`: `hidden`.'],
    ],
  },
  lose: {
    s: 'loses', ing: 'losing',
    means: [['a pierde', 'I’ve **lost** my keys again.']],
    tip: 'Autobuzul, trenul: `miss`, nu `lose`.',
    ex: [
      ['ps', 'My brother often loses his gloves.', 'Fratele meu își pierde des mănușile.'],
      ['past', 'We lost the match on Saturday.', 'Am pierdut meciul de sâmbătă.'],
      ['pp', 'Have you lost something?', 'Ai pierdut ceva?'],
      ['going', 'You’re going to lose your hat in this wind.', 'O să-ți pierzi pălăria pe vântul ăsta.'],
      ['imp', 'Don’t lose the receipt.', 'Să nu pierzi bonul.'],
    ],
    phrases: [['lose weight', 'a slăbi'], ['lose your way', 'a te rătăci'], ['lose touch', 'a pierde legătura']],
    traps: [
      ['I lost the bus this morning.', 'I missed the bus this morning.', 'Autobuz, tren, ocazie: `miss`.'],
      ['I losed my wallet.', 'I lost my wallet.', 'Trecutul: `lost`.'],
      ['I don’t want to loose my job.', 'I don’t want to lose my job.', '`Lose` = a pierde. `Loose` = larg.'],
    ],
  },
  move: {
    s: 'moves', ing: 'moving',
    means: [['a (se) mișca', 'Mimi didn’t **move** all morning.'], ['a muta (ceva)', 'Can you **move** your car, please?'], ['a se muta', 'My sister **moved** to Scotland.']],
    tip: 'Te muți într-un oraș: `move to`.',
    ex: [
      ['ps', 'The queue moves very slowly.', 'Coada înaintează foarte încet.'],
      ['past', 'We moved to a bigger flat last year.', 'Anul trecut ne-am mutat într-un apartament mai mare.'],
      ['pp', 'Have you ever moved house?', 'Te-ai mutat vreodată?'],
      ['can', 'Can you help me move the sofa?', 'Mă ajuți să mut canapeaua?'],
      ['imp', 'Don’t move. There’s a bee on your arm.', 'Nu mișca. Ai o albină pe braț.'],
    ],
    phrases: [['move house', 'a se muta'], ['move in', 'a se muta (într-o locuință)'], ['move out', 'a se muta (dintr-o locuință)']],
    traps: [
      ['We moved in London last year.', 'We moved to London last year.', 'Într-un oraș: `move to`.'],
      ['I moved myself to a new flat.', 'I moved to a new flat.', 'Fără `myself`: doar `move`.'],
    ],
  },
  fall: {
    s: 'falls', ing: 'falling',
    means: [['a cădea', 'The cup **fell** off the table.']],
    tip: 'Scapi ceva din mână: `drop`, nu `fall`.',
    ex: [
      ['ps', 'The leaves fall in autumn.', 'Frunzele cad toamna.'],
      ['past', 'I fell off my bike yesterday.', 'Ieri am căzut de pe bicicletă.'],
      ['pp', 'Has Mimi fallen asleep?', 'A adormit Mimi?'],
      ['can', 'Be careful. You could fall.', 'Ai grijă. Ai putea să cazi.'],
      ['will', 'Don’t worry, the ladder won’t fall.', 'Stai liniștit, scara nu cade.'],
    ],
    phrases: [['fall asleep', 'a adormi'], ['fall in love', 'a se îndrăgosti'], ['fall over', 'a cădea (împiedicându-te)']],
    traps: [
      ['I falled down the stairs.', 'I fell down the stairs.', 'Trecutul: `fell`.'],
      ['I fell my phone.', 'I dropped my phone.', 'Ce scapi din mână: `drop`.'],
      ['I felt off the chair.', 'I fell off the chair.', 'Căzut: `fell`. Simțit: `felt`.'],
    ],
  },

  go: {
    s: 'goes', ing: 'going',
    means: [['a merge', 'We **go** to the café on Fridays.'], ['a pleca', 'Sorry, I have to **go** now.']],
    tip: 'Spre un loc: `go to`. Dar `go home`.',
    ex: [
      ['ps', 'Mimi doesn’t go out when it rains.', 'Mimi nu iese afară când plouă.'],
      ['pc', 'Where are you going?', 'Unde te duci?'],
      ['past', 'We went to the seaside last summer.', 'Am fost la mare vara trecută.'],
      ['pp', 'Priya isn’t here. She’s gone home.', 'Priya nu e aici. A plecat acasă.'],
      ['will', 'I’ll go with you.', 'Merg eu cu tine.'],
    ],
    phrases: [['go home', 'a merge acasă'], ['go shopping', 'a merge la cumpărături'], ['go to bed', 'a merge la culcare'], ['go for a walk', 'a merge la plimbare']],
    traps: [
      ['I went to home.', 'I went home.', 'Fără `to` înainte de `home`.'],
      ['We go to shopping on Saturdays.', 'We go shopping on Saturdays.', '`Go shopping`, `go swimming`: fără `to`.'],
      ['Have you ever gone to Scotland?', 'Have you ever been to Scotland?', '„Ai fost vreodată”: `been`, nu `gone`.'],
    ],
  },
  take: {
    s: 'takes', ing: 'taking',
    means: [['a lua', 'I **take** the bus to work.'], ['a duce undeva', '**Take** these flowers to Mrs Hughes.'], ['a dura', 'The journey **takes** two hours.']],
    tip: 'Spre tine: `bring`. În altă parte: `take`.',
    ex: [
      ['ps', 'It takes ten minutes to walk to the café.', 'Până la cafenea faci zece minute pe jos.'],
      ['past', 'Who took my umbrella?', 'Cine mi-a luat umbrela?'],
      ['pp', 'I’ve taken lots of photos today.', 'Am făcut o grămadă de poze azi.'],
      ['imp', 'Take a coat. It’s cold outside.', 'Ia-ți o haină. E frig afară.'],
      ['can', 'You can’t take photos in the museum.', 'În muzeu nu ai voie să faci poze.'],
    ],
    phrases: [['take a photo', 'a face o poză'], ['take the bus', 'a lua autobuzul'], ['take a break', 'a lua o pauză'], ['It takes an hour.', 'Durează o oră.']],
    traps: [
      ['Can you take me a glass of water?', 'Can you bring me a glass of water?', 'Spre tine: `bring`, nu `take`.'],
      ['I made a photo of the garden.', 'I took a photo of the garden.', 'Pozele: `take a photo`.'],
    ],
  },
  get: {
    s: 'gets', ing: 'getting',
    means: [['a primi', 'I **got** a postcard from Priya.'], ['a ajunge', 'We **got** to the café at nine.'], ['a deveni', 'The days **are getting** shorter.']],
    tip: 'Spre un loc: `get to`. Dar `get home`.',
    ex: [
      ['ps', 'I usually get home at six.', 'De obicei ajung acasă la șase.'],
      ['pc', 'It’s getting dark outside.', 'Afară se întunecă.'],
      ['past', 'Did you get my message?', 'Ai primit mesajul meu?'],
      ['pp', 'My sister has just got home.', 'Sora mea tocmai a ajuns acasă.'],
      ['can', 'I couldn’t get a taxi last night.', 'Aseară n-am reușit să prind un taxi.'],
    ],
    phrases: [['get up', 'a se scula'], ['get home', 'a ajunge acasă'], ['get on the bus', 'a urca în autobuz'], ['get better', 'a se face bine']],
    traps: [
      ['How do I get at the station?', 'How do I get to the station?', 'Ajungi undeva: `get to`.'],
      ['It makes cold.', 'It’s getting cold.', '„Se face frig”: `it’s getting cold`.'],
    ],
  },
  give: {
    s: 'gives', ing: 'giving',
    means: [['a da', 'Can you **give** me your number?']],
    tip: '`Give me the key` = `give the key to me`.',
    ex: [
      ['ps', 'Mrs Hughes gives me roses every summer.', 'Doamna Hughes îmi dă trandafiri în fiecare vară.'],
      ['past', 'My dad gave me this watch.', 'Ceasul ăsta mi l-a dat tata.'],
      ['pp', 'Have you given Mimi her dinner?', 'I-ai dat de mâncare lui Mimi?'],
      ['imp', 'Give me a minute, please.', 'Dă-mi un minut, te rog.'],
      ['can', 'I can’t give you an answer today.', 'Nu-ți pot da un răspuns azi.'],
    ],
    phrases: [['give someone a hand', 'a da cuiva o mână de ajutor'], ['give up', 'a renunța'], ['give back', 'a da înapoi'], ['give someone a call', 'a da cuiva un telefon']],
    traps: [
      ['Give to me the key.', 'Give me the key.', 'Fără `to`: `give me`.'],
      ['I gave the exam yesterday.', 'I took the exam yesterday.', 'Examenul: `take an exam`.'],
    ],
  },
  say: {
    s: 'says', ing: 'saying',
    means: [['a spune, a zice', 'What did Priya **say**?']],
    tip: 'Spui ceva: `say`. Spui cuiva: `tell`.',
    ex: [
      ['ps', 'Tom always says hello to Mimi.', 'Tom o salută mereu pe Mimi.'],
      ['past', 'He didn’t say a word all evening.', 'N-a scos o vorbă toată seara.'],
      ['pp', 'I’ve already said sorry twice.', 'Mi-am cerut deja scuze de două ori.'],
      ['can', 'Could you say that again, please?', 'Poți să repeți, te rog?'],
      ['imp', 'Say thank you to Mrs Hughes.', 'Mulțumește-i doamnei Hughes.'],
    ],
    phrases: [['say hello', 'a saluta'], ['say sorry', 'a-și cere scuze'], ['say yes', 'a spune da, a accepta']],
    traps: [
      ['He said me his name.', 'He told me his name.', 'Spui cuiva: `tell me`.'],
      ['What said Tom?', 'What did Tom say?', 'Întrebarea la trecut: cu `did`.'],
    ],
  },
  tell: {
    s: 'tells', ing: 'telling',
    means: [['a spune cuiva', 'Please **tell** Tom I’m late.'], ['a povesti', '**Tell** me about your holiday.']],
    tip: 'După `tell` vine persoana: `tell me`, `tell Tom`.',
    ex: [
      ['ps', 'My gran tells the best stories.', 'Bunica mea spune cele mai frumoase povești.'],
      ['past', 'Why didn’t you tell me?', 'De ce nu mi-ai spus?'],
      ['pp', 'I’ve told you a hundred times.', 'Ți-am spus de o sută de ori.'],
      ['can', 'Can you tell me the way to the station?', 'Îmi poți spune cum ajung la gară?'],
      ['will', 'I won’t tell anyone.', 'N-o să spun nimănui.'],
    ],
    phrases: [['tell the truth', 'a spune adevărul'], ['tell a story', 'a spune o poveste'], ['tell a lie', 'a spune o minciună']],
    traps: [
      ['Tell to me what happened.', 'Tell me what happened.', 'Fără `to`: `tell me`.'],
      ['He told that he was tired.', 'He said that he was tired.', 'Fără persoană: `say`.'],
    ],
  },
  hear: {
    s: 'hears', ing: 'hearing',
    means: [['a auzi', 'I can **hear** the rain.']],
    tip: 'Auzi fără să vrei: `hear`. Asculți: `listen to`.',
    ex: [
      ['ps', 'My grandad doesn’t hear very well.', 'Bunicul meu nu aude prea bine.'],
      ['can', 'Can you hear me?', 'Mă auzi?'],
      ['past', 'I heard a strange noise last night.', 'Azi-noapte am auzit un zgomot ciudat.'],
      ['pp', 'Have you heard the news?', 'Ai auzit noutățile?'],
      ['will', 'You’ll hear from me soon.', 'O să-ți dau de veste curând.'],
    ],
    phrases: [['hear from someone', 'a primi vești de la cineva'], ['hear about something', 'a afla despre ceva'], ['I can’t hear you.', 'Nu te aud.']],
    traps: [
      ['I am hearing music.', 'I can hear music.', 'Acum: `can hear`.'],
      ['Hear me, please.', 'Listen to me, please.', 'Cu atenție: `listen to`.'],
    ],
  },
  feel: {
    s: 'feels', ing: 'feeling',
    means: [['a se simți', 'I **feel** a bit tired.'], ['a simți', 'I **felt** something on my arm.'], ['a avea chef de', 'I don’t **feel like** cooking tonight.']],
    tip: '„Mă simt” = `I feel`, fără `myself`.',
    ex: [
      ['ps', 'I feel much better today.', 'Azi mă simt mult mai bine.'],
      ['pc', 'How are you feeling?', 'Cum te simți?'],
      ['past', 'I didn’t feel well yesterday.', 'Ieri nu m-am simțit bine.'],
      ['pp', 'I have felt tired all week.', 'M-am simțit obosit toată săptămâna.'],
      ['can', 'I can feel the wind on my face.', 'Simt vântul pe față.'],
    ],
    phrases: [['feel like a cup of tea', 'a avea chef de un ceai'], ['feel at home', 'a se simți ca acasă'], ['feel sorry for someone', 'a-i părea rău de cineva']],
    traps: [
      ['I feel myself tired.', 'I feel tired.', 'Fără `myself`: `I feel`.'],
      ['I don’t feel like to go out.', 'I don’t feel like going out.', 'După `feel like`: `-ing`.'],
    ],
  },
  forget: {
    s: 'forgets', ing: 'forgetting',
    means: [['a uita', 'Sorry, I **forgot** your name.']],
    tip: '„Am uitat cheile acasă” = `I left my keys at home`.',
    ex: [
      ['ps', 'I often forget people’s names.', 'Uit des numele oamenilor.'],
      ['past', 'Did you forget your keys again?', 'Iar ți-ai uitat cheile?'],
      ['pp', 'I’ve forgotten my password.', 'Mi-am uitat parola.'],
      ['imp', 'Don’t forget to call your mum.', 'Nu uita s-o suni pe mama ta.'],
      ['will', 'I’ll never forget that day.', 'N-o să uit niciodată ziua aceea.'],
    ],
    phrases: [['forget to do something', 'a uita să faci ceva'], ['Forget it.', 'Lasă, nu contează.'], ['I almost forgot.', 'Era să uit.']],
    traps: [
      ['I forgot my umbrella at home.', 'I left my umbrella at home.', 'Uitat undeva: `left`, nu `forgot`.'],
      ['Don’t forget calling me.', 'Don’t forget to call me.', 'Ce ai de făcut: `forget to`.'],
    ],
  },
  remember: {
    s: 'remembers', ing: 'remembering',
    means: [['a-și aminti', 'Do you **remember** Sam’s number?'], ['a nu uita să', '**Remember** to lock the door.']],
    tip: '„Amintește-mi” = `remind me`, nu `remember me`.',
    ex: [
      ['ps', 'I don’t remember his name.', 'Nu-mi amintesc cum îl cheamă.'],
      ['past', 'Did you remember to buy milk?', 'Ți-ai amintit să cumperi lapte?'],
      ['pp', 'I’ve just remembered something.', 'Tocmai mi-am amintit ceva.'],
      ['imp', 'Remember to take your keys.', 'Nu uita să-ți iei cheile.'],
      ['can', 'I can still remember my first day at school.', 'Îmi amintesc și acum prima zi de școală.'],
    ],
    phrases: [['remember to do something', 'a nu uita să faci ceva'], ['if I remember correctly', 'dacă îmi amintesc bine'], ['remember someone’s birthday', 'a ține minte ziua cuiva']],
    traps: [
      ['I remember myself that day.', 'I remember that day.', 'Fără `myself`: `I remember`.'],
      ['Remember me to call Tom.', 'Remind me to call Tom.', '„Amintește-mi” = `remind me`.'],
      ['I’m remembering her face.', 'I remember her face.', 'Fără `-ing`: `I remember`.'],
    ],
  },
  meet: {
    s: 'meets', ing: 'meeting',
    means: [['a se întâlni', 'Let’s **meet** at the café.'], ['a cunoaște (prima dată)', 'I **met** Priya on my first day here.']],
    tip: 'Prima dată: `meet`. De mult: `know`.',
    ex: [
      ['ps', 'We meet at the café every Friday.', 'Ne vedem la cafenea în fiecare vineri.'],
      ['pc', 'I’m meeting Sam after work.', 'Mă văd cu Sam după serviciu.'],
      ['past', 'I met my best friend at school.', 'Pe cel mai bun prieten al meu l-am cunoscut la școală.'],
      ['pp', 'Have you met Priya?', 'Ai cunoscut-o pe Priya?'],
      ['can', 'I can’t meet you tomorrow.', 'Mâine nu pot să ne vedem.'],
    ],
    phrases: [['Nice to meet you.', 'Încântat de cunoștință.'], ['meet new people', 'a cunoaște oameni noi'], ['meet for coffee', 'a se vedea la o cafea']],
    traps: [
      ['I knew him last year.', 'I met him last year.', 'Prima dată: `meet`, nu `know`.'],
      ['We met us at the café.', 'We met at the café.', 'Fără `us`: `we met`.'],
    ],
  },
  know: {
    s: 'knows', ing: 'knowing',
    means: [['a ști', 'I **know** her phone number.'], ['a cunoaște', 'I **know** Tom very well.']],
    tip: 'De ani de zile: `I’ve known him for years`.',
    ex: [
      ['ps', 'Do you know Mrs Hughes?', 'O cunoști pe doamna Hughes?'],
      ['past', 'I didn’t know that.', 'Nu știam asta.'],
      ['pp', 'I’ve known Tom for ten years.', 'Îl cunosc pe Tom de zece ani.'],
      ['will', 'We’ll know the results tomorrow.', 'Mâine o să știm rezultatele.'],
      ['can', 'Ask Sam. He should know the way.', 'Întreabă-l pe Sam. El ar trebui să știe drumul.'],
    ],
    phrases: [['I don’t know.', 'Nu știu.'], ['Let me know.', 'Anunță-mă.'], ['as far as I know', 'din câte știu']],
    traps: [
      ['I am knowing the answer.', 'I know the answer.', 'Fără `-ing`: `I know`.'],
      ['I know him since 2010.', 'I’ve known him since 2010.', 'De atunci până acum: `I’ve known`.'],
    ],
  },
  plan: {
    s: 'plans', ing: 'planning',
    means: [['a plănui', 'I need to **plan** my week.'], ['a avea de gând', 'We **plan** to move next year.']],
    tip: 'Se dublează `n`: `planning`, `planned`.',
    ex: [
      ['ps', 'We usually plan our holidays in January.', 'De obicei ne plănuim vacanțele în ianuarie.'],
      ['pc', 'What are you planning to do this weekend?', 'Ce ai de gând să faci weekendul ăsta?'],
      ['past', 'I didn’t plan to stay so long.', 'N-aveam de gând să stau atât.'],
      ['pp', 'Tom has planned a party for Saturday.', 'Tom a plănuit o petrecere pentru sâmbătă.'],
      ['can', 'We should plan the trip together.', 'Ar trebui să plănuim excursia împreună.'],
    ],
    phrases: [['plan a trip', 'a plănui o călătorie'], ['plan to do something', 'a avea de gând să faci ceva'], ['plan ahead', 'a plănui din timp']],
    traps: [
      ['I planed everything.', 'I planned everything.', 'Cu doi `n`: `planned`.'],
      ['I’m planning visit my aunt.', 'I’m planning to visit my aunt.', 'După `plan`: `to` + verb.'],
    ],
  },
  send: {
    s: 'sends', ing: 'sending',
    means: [['a trimite', 'Can you **send** me the address?']],
    tip: '`Send me the photo` = `send the photo to me`.',
    ex: [
      ['ps', 'My mum sends me a message every morning.', 'Mama îmi trimite un mesaj în fiecare dimineață.'],
      ['past', 'I sent you an email last night.', 'Ți-am trimis un e-mail aseară.'],
      ['pp', 'Have you sent the card to your gran?', 'I-ai trimis felicitarea bunicii tale?'],
      ['will', 'I’ll send you the photos tomorrow.', 'Îți trimit pozele mâine.'],
      ['imp', 'Don’t send it yet.', 'Nu-l trimite încă.'],
    ],
    phrases: [['send a message', 'a trimite un mesaj'], ['send a parcel', 'a trimite un colet'], ['Send my love to your mum.', 'Transmite-i mamei tale salutări cu drag.']],
    traps: [
      ['I sended the letter.', 'I sent the letter.', '`Send` e neregulat: `sent`.'],
      ['Send to me the photo.', 'Send me the photo.', 'Fără `to`: `send me`.'],
    ],
  },
  decide: {
    s: 'decides', ing: 'deciding',
    means: [['a hotărî', 'I’ve **decided** to learn Spanish.']],
    tip: '„M-am hotărât” = `I’ve decided`, fără `me`.',
    ex: [
      ['ps', 'My sister always decides where we go.', 'Mereu sora mea hotărăște unde mergem.'],
      ['past', 'We decided to stay at home.', 'Am hotărât să rămânem acasă.'],
      ['pp', 'Have you decided what to order?', 'Te-ai hotărât ce comanzi?'],
      ['can', 'I can’t decide which one to buy.', 'Nu mă pot hotărî pe care să-l cumpăr.'],
      ['will', 'We’ll decide after dinner.', 'Hotărâm după cină.'],
    ],
    phrases: [['decide to do something', 'a hotărî să faci ceva'], ['decide what to do', 'a hotărî ce să faci'], ['make a decision', 'a lua o hotărâre']],
    traps: [
      ['I decided staying at home.', 'I decided to stay at home.', 'După `decide`: `to` + verb.'],
      ['I have decided yesterday.', 'I decided yesterday.', 'Cu `yesterday`: trecutul simplu.'],
      ['I can’t decide me.', 'I can’t decide.', 'Fără `me`: `I can’t decide`.'],
    ],
  },
  prepare: {
    s: 'prepares', ing: 'preparing',
    means: [['a pregăti', 'I’ll **prepare** dinner tonight.'], ['a se pregăti pentru', 'We’re **preparing for** the winter.']],
    tip: 'Te pregătești: `prepare for` sau `get ready for`.',
    ex: [
      ['ps', 'Tom prepares the sandwiches every morning.', 'Tom pregătește sandvișurile în fiecare dimineață.'],
      ['pc', 'I’m preparing for an exam.', 'Mă pregătesc pentru un examen.'],
      ['past', 'Who prepared this lovely dinner?', 'Cine a pregătit cina asta minunată?'],
      ['pp', 'We haven’t prepared anything yet.', 'Încă n-am pregătit nimic.'],
      ['going', 'I’m going to prepare the spare room for my sister.', 'O să pregătesc camera de oaspeți pentru sora mea.'],
    ],
    phrases: [['prepare dinner', 'a pregăti cina'], ['prepare for an exam', 'a se pregăti pentru un examen'], ['be prepared', 'a fi pregătit']],
    traps: [
      ['We prepared us for the trip.', 'We got ready for the trip.', 'Fără `us`. Mai firesc: `got ready`.'],
      ['I’m preparing my exam.', 'I’m preparing for my exam.', 'Înveți pentru examen: `prepare for`.'],
    ],
  },
  promise: {
    s: 'promises', ing: 'promising',
    means: [['a promite', 'Sam **promised** to wait for me.']],
    tip: '„Promit că vin” = `I promise I’ll come`.',
    ex: [
      ['ps', 'I promise I’ll be careful.', 'Promit că o să fiu atent.'],
      ['past', 'You promised to help me.', 'Ai promis că mă ajuți.'],
      ['pp', 'Tom hasn’t promised anything.', 'Tom n-a promis nimic.'],
      ['can', 'Can you promise me that?', 'Poți să-mi promiți asta?'],
      ['imp', 'Promise me you won’t tell anyone.', 'Promite-mi că nu spui nimănui.'],
    ],
    phrases: [['I promise.', 'Promit.'], ['keep a promise', 'a-și ține promisiunea'], ['break a promise', 'a nu-și ține promisiunea']],
    traps: [
      ['I promise I come tomorrow.', 'I promise I’ll come tomorrow.', 'Pentru viitor: `I’ll come`.'],
      ['She promised to me a present.', 'She promised me a present.', 'Fără `to`: `promised me`.'],
    ],
  },
  return: {
    s: 'returns', ing: 'returning',
    means: [['a se întoarce', 'We **returned** from Spain on Sunday.'], ['a da înapoi', 'I **returned** the jacket to the shop.']],
    tip: 'În vorbire, mai des: `come back`, `give back`.',
    ex: [
      ['ps', 'Sam returns home at six in the morning.', 'Sam se întoarce acasă la șase dimineața.'],
      ['past', 'When did you return from your holiday?', 'Când te-ai întors din concediu?'],
      ['pp', 'I haven’t returned the book to the library yet.', 'Încă n-am dus cartea înapoi la bibliotecă.'],
      ['will', 'Dr Okafor will return on Monday.', 'Dr Okafor se întoarce luni.'],
      ['can', 'You must return the key by Friday.', 'Trebuie să dai cheia înapoi până vineri.'],
    ],
    phrases: [['return home', 'a se întoarce acasă'], ['return a book', 'a returna o carte'], ['return a call', 'a suna pe cineva înapoi'], ['a return ticket', 'un bilet dus-întors']],
    traps: [
      ['I returned back home.', 'I returned home.', 'Fără `back`: `return` e deja „înapoi”.'],
      ['I’ll return you the book tomorrow.', 'I’ll return the book to you tomorrow.', 'Persoana la sfârșit, cu `to`.'],
    ],
  },

  borrow: {
    s: 'borrows', ing: 'borrowing',
    means: [['a lua cu împrumut', 'I **borrowed** a book from Tom.']],
    tip: 'Iei de la cineva: `borrow`. Dai cuiva: `lend`.',
    ex: [
      ['ps', 'My sister often borrows my clothes.', 'Sora mea îmi ia des hainele.'],
      ['can', 'Can I borrow your pen for a minute?', 'Îmi dai puțin pixul?'],
      ['past', 'I borrowed a ladder from Mrs Hughes.', 'Am împrumutat o scară de la doamna Hughes.'],
      ['pp', 'Have you ever borrowed money from a friend?', 'Ai luat vreodată bani cu împrumut de la un prieten?'],
      ['going', 'I’m not going to borrow his car again.', 'Nu-i mai cer mașina împrumut.'],
    ],
    phrases: [
      ['borrow a book from the library', 'a împrumuta o carte de la bibliotecă'],
      ['borrow money from the bank', 'a lua bani cu împrumut de la bancă'],
      ['Can I borrow…?', 'Îmi împrumuți…?'],
    ],
    traps: [
      ['Can you borrow me your pen?', 'Can you lend me your pen?', 'Cel care dă: `lend`.'],
      ['Can I borrow from you a pen?', 'Can I borrow a pen from you?', 'Întâi lucrul, apoi `from you`.'],
    ],
  },
  lend: {
    s: 'lends', ing: 'lending',
    means: [['a da cu împrumut', 'I can **lend** you a book.']],
    tip: 'Dai cuiva: `lend`. Iei de la cineva: `borrow`.',
    ex: [
      ['ps', 'Priya never lends money to anyone.', 'Priya nu împrumută niciodată bani nimănui.'],
      ['can', 'Could you lend me your umbrella?', 'Mi-ai putea împrumuta umbrela?'],
      ['past', 'Tom lent me his bike last week.', 'Tom mi-a împrumutat bicicleta săptămâna trecută.'],
      ['pp', 'I’ve lent my car to my brother.', 'I-am împrumutat mașina fratelui meu.'],
      ['will', 'Don’t worry, I’ll lend you some money.', 'Nu-ți face griji, îți împrumut eu niște bani.'],
    ],
    phrases: [
      ['lend a hand', 'a da o mână de ajutor'],
      ['lend someone money', 'a împrumuta pe cineva cu bani'],
      ['lend a book to a friend', 'a împrumuta o carte unui prieten'],
    ],
    traps: [
      ['I lended him my bike.', 'I lent him my bike.', 'Trecutul e `lent`.'],
      ['Can you borrow me ten pounds?', 'Can you lend me ten pounds?', 'Cel care dă: `lend`.'],
    ],
  },
  allow: {
    s: 'allows', ing: 'allowing',
    means: [['a permite, a lăsa', 'Priya doesn’t **allow** dogs in the shop.']],
    tip: '„Am voie să” = `I’m allowed to`.',
    ex: [
      ['ps', 'Mimi isn’t allowed on the bed.', 'Mimi n-are voie în pat.'],
      ['past', 'My boss allowed me to leave early.', 'Șeful m-a lăsat să plec mai devreme.'],
      ['pp', 'The doctor has allowed him to go home.', 'Doctorul i-a dat voie să meargă acasă.'],
      ['will', 'Will they allow us to bring food?', 'O să ne lase să aducem mâncare?'],
      ['can', 'You shouldn’t allow your dog on the sofa.', 'N-ar trebui să-ți lași câinele pe canapea.'],
    ],
    phrases: [
      ['be allowed to', 'a avea voie să'],
      ['Smoking isn’t allowed.', 'Fumatul este interzis.'],
      ['allow someone in', 'a lăsa pe cineva să intre'],
    ],
    traps: [
      ['My mum doesn’t allow me go out.', 'My mum doesn’t allow me to go out.', 'După `allow me` vine `to`.'],
      ['It’s not allowed to smoke here.', 'You aren’t allowed to smoke here.', 'Cine n-are voie e subiectul: `you`.'],
      ['I’m not allow to park here.', 'I’m not allowed to park here.', 'Se spune `allowed`, cu `-ed`.'],
    ],
  },
  climb: {
    s: 'climbs', ing: 'climbing',
    means: [['a urca cu efort', 'Mimi **climbed** the tree.']],
    tip: '`Climb` e cu efort. În autobuz: `get on`.',
    ex: [
      ['ps', 'Mimi climbs the fence every morning.', 'Mimi se cațără pe gard în fiecare dimineață.'],
      ['pc', 'Why is Tom climbing the ladder?', 'De ce se urcă Tom pe scară?'],
      ['past', 'We climbed the hill behind the village.', 'Am urcat dealul din spatele satului.'],
      ['pp', 'I’ve never climbed a mountain.', 'N-am urcat niciodată pe munte.'],
      ['can', 'My grandma can’t climb the stairs any more.', 'Bunica nu mai poate urca scările.'],
    ],
    phrases: [
      ['climb the stairs', 'a urca scările'],
      ['climb a tree', 'a se cățăra într-un copac'],
      ['climb into bed', 'a se băga în pat'],
    ],
    traps: [
      ['I climbed in the bus.', 'I got on the bus.', 'În autobuz urci cu `get on`.'],
      ['I climbed to the fifth floor by lift.', 'I went up to the fifth floor by lift.', 'Cu liftul, fără efort: `go up`.'],
    ],
  },
  check: {
    s: 'checks', ing: 'checking',
    means: [['a verifica', 'Please **check** your answers.'], ['a se uita la', 'I’ll just **check** my phone.']],
    tip: '„A controla” (acte, bilete) = `check`.',
    ex: [
      ['ps', 'Tom checks the oven before he goes home.', 'Tom verifică cuptorul înainte să plece acasă.'],
      ['pc', 'Sorry, I’m just checking my messages.', 'Scuze, mă uit puțin la mesaje.'],
      ['past', 'Did you check the back door?', 'Ai verificat ușa din spate?'],
      ['pp', 'I haven’t checked my email today.', 'Nu mi-am verificat e-mailul azi.'],
      ['can', 'You should check the bill before you pay.', 'Ar trebui să verifici nota înainte să plătești.'],
    ],
    phrases: [
      ['check the time', 'a te uita la ceas'],
      ['check the weather', 'a vedea cum e vremea'],
      ['check in at the hotel', 'a te caza la hotel'],
    ],
    traps: [
      ['The police controlled my passport.', 'The police checked my passport.', '`Control` nu înseamnă „a verifica”.'],
      ['I can’t talk, I check my email.', 'I can’t talk, I’m checking my email.', 'Chiar acum: `I’m checking`.'],
    ],
  },
  repair: {
    s: 'repairs', ing: 'repairing',
    means: [['a repara', 'We need to **repair** the roof.']],
    tip: 'În vorbire se aude mai des `fix`.',
    ex: [
      ['ps', 'Sam repairs old bikes in his free time.', 'Sam repară biciclete vechi în timpul liber.'],
      ['past', 'They repaired the road last summer.', 'Au reparat drumul vara trecută.'],
      ['pp', 'Has anyone repaired the lift yet?', 'A reparat cineva liftul?'],
      ['going', 'We’re going to repair the fence in spring.', 'La primăvară o să reparăm gardul.'],
      ['can', 'I can’t repair this old watch.', 'Nu pot să repar ceasul ăsta vechi.'],
    ],
    phrases: [
      ['get the car repaired', 'a da mașina la reparat'],
      ['repair the damage', 'a repara stricăciunile'],
      ['a repair shop', 'un atelier de reparații'],
    ],
    traps: [
      ['I repaired my car at the garage.', 'I had my car repaired at the garage.', 'L-a reparat mecanicul: `had it repaired`.'],
      ['We must to repair the door.', 'We must repair the door.', 'După `must`, fără `to`.'],
    ],
  },
  compare: {
    s: 'compares', ing: 'comparing',
    means: [['a compara', 'I **compared** the two jackets.']],
    tip: 'Cu ce compari: `with` sau `to`.',
    ex: [
      ['ps', 'Priya always compares prices before buying anything.', 'Priya compară mereu prețurile înainte să cumpere ceva.'],
      ['pc', 'We’re comparing two flats in the centre.', 'Comparăm două apartamente din centru.'],
      ['past', 'I compared my answers with Tom’s.', 'Mi-am comparat răspunsurile cu ale lui Tom.'],
      ['pp', 'Have you compared the two offers?', 'Ai comparat cele două oferte?'],
      ['imp', 'Don’t compare yourself to your sister.', 'Nu te compara cu sora ta.'],
    ],
    phrases: [
      ['compare prices', 'a compara prețurile'],
      ['compared to last year', 'față de anul trecut'],
      ['compare notes', 'a face schimb de impresii'],
    ],
    traps: [
      ['Let’s compare between the two phones.', 'Let’s compare the two phones.', 'Direct, fără `between`.'],
      ['I compare always the prices.', 'I always compare the prices.', '`Always` stă înaintea verbului.'],
    ],
  },
  grow: {
    s: 'grows', ing: 'growing',
    means: [['a crește', 'Children **grow** very quickly.'], ['a cultiva', 'We **grow** tomatoes in the garden.']],
    tip: 'Unde ai crescut: `I grew up in…`',
    ex: [
      ['ps', 'Mrs Hughes grows roses in her garden.', 'Doamna Hughes cultivă trandafiri în grădină.'],
      ['pc', 'My hair is growing really fast.', 'Îmi crește părul foarte repede.'],
      ['past', 'I grew up in a small town.', 'Am crescut într-un oraș mic.'],
      ['pp', 'The tomatoes haven’t grown much this year.', 'Roșiile n-au crescut prea mult anul ăsta.'],
      ['can', 'Can you grow lemons in England?', 'Se pot cultiva lămâi în Anglia?'],
    ],
    phrases: [
      ['grow up', 'a crește mare'],
      ['grow vegetables', 'a cultiva legume'],
      ['grow a beard', 'a-și lăsa barbă'],
    ],
    traps: [
      ['My grandparents grew me.', 'My grandparents brought me up.', 'Pe cineva îl crești: `bring up`.'],
      ['I growed up in a village.', 'I grew up in a village.', 'Neregulat: `grew`, `grown`.'],
    ],
  },
  shine: {
    s: 'shines', ing: 'shining',
    means: [['a străluci, a lumina', 'The sun **shines** a lot in Spain.']],
    tip: '„E soare” = `the sun is shining`.',
    ex: [
      ['ps', 'The moon shines through my window at night.', 'Noaptea, lumina lunii intră pe fereastra mea.'],
      ['pc', 'The sun is shining. Let’s go out.', 'E soare. Hai să ieșim.'],
      ['past', 'The sun shone all day yesterday.', 'Ieri a fost soare toată ziua.'],
      ['pp', 'The sun hasn’t shone for days.', 'De câteva zile n-a mai ieșit soarele.'],
      ['can', 'Can you shine your torch over here?', 'Poți să luminezi încoace cu lanterna?'],
    ],
    phrases: [
      ['shine a torch on something', 'a lumina ceva cu lanterna'],
      ['shine brightly', 'a străluci puternic'],
      ['rain or shine', 'pe orice vreme'],
    ],
    traps: [
      ['The sun shined all day.', 'The sun shone all day.', 'Trecutul e `shone`.'],
      ['Today is sun.', 'The sun is shining today.', 'Nu `is sun`. Merge și `it’s sunny`.'],
    ],
  },
  rise: {
    s: 'rises', ing: 'rising',
    means: [['a răsări', 'What time does the sun **rise**?'], ['a crește, a urca', 'Prices **rise** every year.']],
    tip: '`Rise` urcă singur. Ridici tu: `raise`.',
    ex: [
      ['ps', 'The sun rises early in summer.', 'Vara, soarele răsare devreme.'],
      ['pc', 'The water in the river is rising.', 'Apa râului crește.'],
      ['past', 'Prices rose a lot last year.', 'Anul trecut prețurile au crescut mult.'],
      ['pp', 'Has the rent risen again?', 'Iar a crescut chiria?'],
      ['will', 'The bread won’t rise in a cold kitchen.', 'Aluatul nu crește într-o bucătărie rece.'],
    ],
    phrases: [
      ['The sun rises in the east.', 'Soarele răsare la est.'],
      ['prices rise', 'cresc prețurile'],
      ['a pay rise', 'o mărire de salariu'],
    ],
    traps: [
      ['They rose the prices again.', 'They raised the prices again.', 'Ridici tu ceva: `raise`.'],
      ['The sun rised at six.', 'The sun rose at six.', 'Neregulat: `rose`, `risen`.'],
    ],
  },
  reach: {
    s: 'reaches', ing: 'reaching',
    means: [['a ajunge la', 'We **reached** London at ten.'], ['a ajunge cu mâna', 'Can you **reach** that cup?']],
    tip: 'Fără `at`, fără `to`: `reach the station`.',
    ex: [
      ['ps', 'This bus reaches the centre in ten minutes.', 'Autobuzul ăsta ajunge în centru în zece minute.'],
      ['past', 'We reached the top of the hill at noon.', 'Am ajuns în vârful dealului la prânz.'],
      ['pp', 'Have you reached the station yet?', 'Ai ajuns la gară?'],
      ['can', 'I can’t reach the top shelf.', 'Nu ajung la raftul de sus.'],
      ['will', 'You’ll reach the village before dark.', 'Ajungi în sat înainte să se întunece.'],
    ],
    phrases: [
      ['You can reach me on this number.', 'Mă găsești la numărul ăsta.'],
      ['reach a decision', 'a lua o hotărâre'],
      ['out of reach', 'unde nu ajungi cu mâna'],
    ],
    traps: [
      ['We reached at the hotel late.', 'We reached the hotel late.', 'Fără `at`: `reach the hotel`.'],
    ],
  },
  win: {
    s: 'wins', ing: 'winning',
    means: [['a câștiga', 'Our team **won** on Saturday.']],
    tip: 'Banii de la muncă: `earn`, nu `win`.',
    ex: [
      ['ps', 'Tom always wins at cards.', 'Tom câștigă mereu la cărți.'],
      ['pc', 'Who’s winning the match?', 'Cine câștigă meciul?'],
      ['past', 'My sister won a prize at school.', 'Sora mea a câștigat un premiu la școală.'],
      ['pp', 'I’ve never won anything.', 'N-am câștigat niciodată nimic.'],
      ['will', 'Do you think they’ll win?', 'Crezi că o să câștige?'],
    ],
    phrases: [
      ['win the lottery', 'a câștiga la loterie'],
      ['win a race', 'a câștiga o cursă'],
      ['win a game of chess', 'a câștiga o partidă de șah'],
    ],
    traps: [
      ['How much do you win a month?', 'How much do you earn a month?', 'Salariul se câștigă cu `earn`.'],
      ['We won them 3–0.', 'We beat them 3–0.', 'Pe adversar îl învingi: `beat`.'],
    ],
  },
  'set off': {
    s: 'sets off', ing: 'setting off',
    means: [['a porni la drum', 'They **set off** for the coast.']],
    tip: 'La trecut rămâne `set off`.',
    ex: [
      ['ps', 'Sam sets off for work at ten every night.', 'Sam pleacă la muncă în fiecare seară la zece.'],
      ['past', 'We set off early to miss the traffic.', 'Am plecat devreme ca să scăpăm de trafic.'],
      ['pp', 'Have they set off yet?', 'Au pornit deja la drum?'],
      ['going', 'We’re going to set off after breakfast.', 'Pornim la drum după micul dejun.'],
      ['imp', 'Don’t set off without a map.', 'Nu pleca la drum fără hartă.'],
    ],
    phrases: [
      ['set off early', 'a pleca devreme'],
      ['set off on a journey', 'a porni la drum'],
      ['set off for home', 'a o porni spre casă'],
    ],
    traps: [
      ['We setted off at six.', 'We set off at six.', '`Set` nu se schimbă.'],
      ['When you set off?', 'When did you set off?', 'Întrebare la trecut: cu `did`.'],
    ],
  },
  'come back': {
    s: 'comes back', ing: 'coming back',
    means: [['a se întoarce', 'When are you **coming back**?']],
    tip: 'Aici: `come back`. Acolo: `go back`.',
    ex: [
      ['ps', 'What time does your dad come back from work?', 'La ce oră se întoarce tatăl tău de la muncă?'],
      ['past', 'She came back from Spain last week.', 'S-a întors din Spania săptămâna trecută.'],
      ['pp', 'Mimi hasn’t come back yet.', 'Mimi nu s-a întors încă.'],
      ['will', 'I’ll come back in five minutes.', 'Mă întorc în cinci minute.'],
      ['imp', 'Come back later, please. We’re closed.', 'Reveniți mai târziu, vă rog. Acum e închis.'],
    ],
    phrases: [
      ['come back home', 'a se întoarce acasă'],
      ['come back from holiday', 'a se întoarce din concediu'],
      ['come back later', 'a reveni mai târziu'],
    ],
    traps: [
      ['I come back in five minutes.', 'I’ll come back in five minutes.', 'Promiți pe loc: `I’ll`.'],
      ['I loved Rome. I want to come back there.', 'I loved Rome. I want to go back there.', 'Acolo, unde nu ești: `go back`.'],
    ],
  },
  'say goodbye': {
    s: 'says goodbye', ing: 'saying goodbye',
    means: [['a-și lua rămas-bun', 'She left without **saying goodbye**.']],
    tip: 'Rămas-bun de la Tom: `say goodbye to Tom`.',
    ex: [
      ['ps', 'My son never says goodbye when he leaves.', 'Fiul meu nu-și ia niciodată la revedere când pleacă.'],
      ['past', 'We said goodbye at the station.', 'Ne-am luat rămas-bun la gară.'],
      ['pp', 'Have you said goodbye to Grandma?', 'Ți-ai luat la revedere de la bunica?'],
      ['can', 'I must say goodbye to Tom first.', 'Întâi trebuie să-mi iau la revedere de la Tom.'],
      ['imp', 'Let’s say goodbye here.', 'Hai să ne luăm rămas-bun aici.'],
    ],
    phrases: [
      ['say goodbye to someone', 'a-și lua rămas-bun de la cineva'],
      ['wave goodbye', 'a face cu mâna la plecare'],
      ['Say hello to Tom for me.', 'Salută-l pe Tom din partea mea.'],
    ],
    traps: [
      ['I said goodbye from my friends.', 'I said goodbye to my friends.', 'Cu `to`, nu cu `from`.'],
      ['I told goodbye to her.', 'I said goodbye to her.', 'Cu `say`, nu cu `tell`.'],
    ],
  },
  'look forward to': {
    s: 'looks forward to', ing: 'looking forward to',
    means: [['a aștepta cu drag', 'I’m **looking forward to** the party.']],
    tip: 'După `to`, verbul ia `-ing`: `to seeing you`.',
    ex: [
      ['ps', 'Sam looks forward to his days off.', 'Sam își așteaptă cu drag zilele libere.'],
      ['pc', 'Are you looking forward to seeing your family?', 'Abia aștepți să-ți vezi familia?'],
      ['past', 'Mrs Hughes always looked forward to Sundays.', 'Doamna Hughes aștepta mereu cu drag duminicile.'],
      ['pp', 'I’ve never looked forward to Mondays.', 'N-am așteptat niciodată cu drag zilele de luni.'],
      ['can', 'We can look forward to some sun this weekend.', 'La sfârșitul săptămânii ne putem bucura de puțin soare.'],
    ],
    phrases: [
      ['I’m looking forward to it.', 'Abia aștept.'],
      ['I look forward to hearing from you.', 'Aștept cu interes răspunsul dumneavoastră.'],
      ['look forward to the holidays', 'a aștepta cu drag vacanța'],
    ],
    traps: [
      ['I’m looking forward to see you.', 'I’m looking forward to seeing you.', '`To` e prepoziție: `to seeing`.'],
      ['We’re looking forward the weekend.', 'We’re looking forward to the weekend.', 'Lipsește `to`.'],
    ],
  },
  miss: {
    s: 'misses', ing: 'missing',
    means: [['a-i fi dor de', 'I **miss** my family.'], ['a pierde, a rata', 'Hurry, or we’ll **miss** the train.']],
    tip: '„Mi-e dor de tine” = `I miss you`.',
    ex: [
      ['ps', 'I don’t miss my old job at all.', 'Nu-mi lipsește deloc vechiul serviciu.'],
      ['past', 'Sorry, I missed your call.', 'Scuze, n-am răspuns când m-ai sunat.'],
      ['pp', 'Have you ever missed a flight?', 'Ai pierdut vreodată avionul?'],
      ['will', 'You’ll miss Mimi when you’re away.', 'O să-ți fie dor de Mimi cât ești plecat.'],
      ['can', 'We mustn’t miss the last bus.', 'Să nu pierdem ultimul autobuz.'],
    ],
    phrases: [
      ['miss the bus', 'a pierde autobuzul'],
      ['I miss you.', 'Mi-e dor de tine.'],
      ['You can’t miss it.', 'N-ai cum să nu-l vezi.'],
    ],
    traps: [
      ['I lost the bus.', 'I missed the bus.', 'Un autobuz ratat: `miss`, nu `lose`.'],
      ['You miss me a lot.', 'I miss you a lot.', '„Îmi lipsești” = `I miss you`.'],
    ],
  },
  fly: {
    s: 'flies', ing: 'flying',
    means: [['a zbura', 'A bird **flew** into the kitchen.'], ['a merge cu avionul', 'We **flew** to Bucharest last summer.']],
    tip: '`Fly` spune singur „cu avionul”.',
    ex: [
      ['ps', 'My sister flies to Spain every summer.', 'Sora mea merge cu avionul în Spania în fiecare vară.'],
      ['pc', 'Are you flying or going by train?', 'Mergi cu avionul sau cu trenul?'],
      ['past', 'The birds flew away when Mimi came out.', 'Păsările au zburat când a ieșit Mimi.'],
      ['pp', 'I’ve never flown before.', 'N-am mai zburat niciodată.'],
      ['going', 'We’re going to fly to Rome in May.', 'În mai mergem cu avionul la Roma.'],
    ],
    phrases: [
      ['fly a kite', 'a înălța un zmeu'],
      ['fly to London', 'a merge cu avionul la Londra'],
      ['Time flies.', 'Timpul zboară.'],
    ],
    traps: [
      ['I flied to Rome last year.', 'I flew to Rome last year.', 'Neregulat: `flew`, `flown`.'],
      ['We went with the plane to Rome.', 'We flew to Rome.', 'Nu `with the plane`: `we flew`.'],
      ['She flys a lot for work.', 'She flies a lot for work.', 'Cu `she`: `flies`, cu `-ies`.'],
    ],
  },
};
